// Code generated by epmp-sdk. DO NOT EDIT.

package tenantdocument

import (
	"github.com/epmp/backend/internal/modules/tenantdocument/delivery/http"
	"github.com/epmp/backend/internal/modules/tenantdocument/repository"
	"github.com/epmp/backend/internal/modules/tenantdocument/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all TenantDocument dependencies.
type Module struct {
	Handler *http.TenantDocumentHandler
}

// NewModule creates and wires all TenantDocument dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.TenantDocumentRepository = repository.NewTenantDocumentRepositoryImpl(db)
	svc := service.NewTenantDocumentService(repo)
	handler := http.NewTenantDocumentHandler(svc)

	log.Info().Str("module", "tenantdocument").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all TenantDocument routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/tenant_documents")
	http.RegisterTenantDocumentRoutes(g, m.Handler)
}
