// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Bed,
  BedListResponse,
  CreateBedRequest,
  UpdateBedRequest,
  BedQueryParams,
} from "../types";

const BASE_PATH = "/beds";
export async function fetchBeds(params?: BedQueryParams): Promise<BedListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: BedListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchBedById(id: string): Promise<Bed> {
  const res = await api.get<{ success: boolean; data: Bed }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createBed(data: CreateBedRequest): Promise<Bed> {
  const res = await api.post<{ success: boolean; data: Bed }>(BASE_PATH, data);
  return res.data;
}
export async function updateBed(id: string, data: UpdateBedRequest): Promise<Bed> {
  const res = await api.put<{ success: boolean; data: Bed }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteBed(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
