// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/deposit/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// DepositRepositoryImpl implements DepositRepository using PostgreSQL.
type DepositRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewDepositRepositoryImpl creates a new DepositRepositoryImpl.
func NewDepositRepositoryImpl(db *pgxpool.Pool) *DepositRepositoryImpl {
	return &DepositRepositoryImpl{db: db}
}

// Ensure DepositRepositoryImpl implements domain repository interface.
var _ DepositRepository = (*DepositRepositoryImpl)(nil)

func (r *DepositRepositoryImpl) Save(ctx context.Context, e *entity.Deposit) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO deposits (organization_id, contract_id, tenant_id, amount, status, collection_date, refund_date, notes)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
			RETURNING id`,
			e.OrganizationId, e.ContractId, e.TenantId, e.Amount, e.Status, e.CollectionDate, e.RefundDate, e.Notes,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE deposits
		SET    organization_id=$1, contract_id=$2, tenant_id=$3, amount=$4, status=$5, collection_date=$6, refund_date=$7, notes=$8
		WHERE  id=$9 AND deleted_at IS NULL`,
		e.OrganizationId, e.ContractId, e.TenantId, e.Amount, e.Status, e.CollectionDate, e.RefundDate, e.Notes, e.Id,
	)
	return err
}

func (r *DepositRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Deposit, error) {
	e := &entity.Deposit{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, contract_id, tenant_id, amount, status, collection_date, refund_date, notes, deleted_at
		FROM   deposits
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.ContractId, &e.TenantId, &e.Amount, &e.Status, &e.CollectionDate, &e.RefundDate, &e.Notes, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("deposit repository: find by id: %w", err)
	}
	return e, nil
}

func (r *DepositRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Deposit, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, contract_id, tenant_id, amount, status, collection_date, refund_date, notes, deleted_at
		FROM   deposits
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("deposit repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Deposit
	for rows.Next() {
		e := &entity.Deposit{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.ContractId, &e.TenantId, &e.Amount, &e.Status, &e.CollectionDate, &e.RefundDate, &e.Notes, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *DepositRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE deposits SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
