// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/deposit/entity"
)

// DepositRepository is the contract for persisting Deposit aggregates.
type DepositRepository interface {
	// Save persists a Deposit entity.
	Save(ctx context.Context, e *entity.Deposit) error

	// FindByID retrieves a Deposit by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Deposit, error)

	// FindAll retrieves a paginated list of Deposit entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Deposit, error)

	// Delete removes a Deposit by its primary key.
	Delete(ctx context.Context, id string) error
}
