// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const reservationSchema = z.object({
  organization_id: z.string().optional(),
  id: z.string(),
  tenant_id: z.string().min(1, "Tenant is required"),
  property_id: z.string().min(1, "Property is required"),
  room_id: z.string().min(1, "Room is required"),
  status: z.enum(["Draft", "Pending", "Confirmed", "Cancelled", "Expired"]),
  check_in_date: z.string().min(1, "Check-in date is required"),
  check_out_date: z.string().optional(),
  booking_fee: z.coerce.number().min(0, "Booking fee must be >= 0"),
  notes: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createReservationSchema = reservationSchema.omit({
  id: true,
  organization_id: true,
  created_at: true,
  updated_at: true,
});

export const updateReservationSchema = createReservationSchema.partial();

export type ReservationFormData = z.infer<typeof reservationSchema>;
export type CreateReservationFormData = z.infer<typeof createReservationSchema>;
export type UpdateReservationFormData = z.infer<typeof updateReservationSchema>;
