// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const roomTypeSchema = z.object({
  organization_id: z.string().optional(),
  id: z.string(),
  name: z.string().min(1, "Name is required").max(100),
  description: z.string().optional(),
  base_price: z.coerce.number().min(0, "Base price must be >= 0"),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createRoomTypeSchema = roomTypeSchema.omit({
  id: true,
  organization_id: true,
  created_at: true,
  updated_at: true,
});

export const updateRoomTypeSchema = createRoomTypeSchema.partial();

export type RoomTypeFormData = z.infer<typeof roomTypeSchema>;
export type CreateRoomTypeFormData = z.infer<typeof createRoomTypeSchema>;
export type UpdateRoomTypeFormData = z.infer<typeof updateRoomTypeSchema>;
