// Code generated by epmp-sdk. DO NOT EDIT.

export interface TenantDocument {
  organization_id: string;
  id: string;
  tenant_id: string;
  document_type: string;
  file_url: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface TenantDocumentListResponse {
  data: TenantDocument[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreateTenantDocumentRequest {
  organization_id: string;
  tenant_id: string;
  document_type: string;
  file_url: string;
}

export interface UpdateTenantDocumentRequest {
  organization_id: string;
  tenant_id: string;
  document_type: string;
  file_url: string;
}

export interface TenantDocumentQueryParams {
  page?: number;
  per_page?: number;
  sort?: string;
  order?: "asc" | "desc";
  search?: string;
  organization_id?: string;
  tenant_id?: string;
}
