// Code generated by epmp-sdk. DO NOT EDIT.

export interface Penalty {
  organization_id: string;
  id: string;
  invoice_id: string;
  amount: number;
  status: string;
  penalty_date: string;
  description: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface PenaltyListResponse {
  data: Penalty[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreatePenaltyRequest {
  organization_id: string;
  invoice_id: string;
  amount: number;
  status: string;
  penalty_date: string;
  description: string;
}

export interface UpdatePenaltyRequest {
  organization_id: string;
  invoice_id: string;
  amount: number;
  status: string;
  penalty_date: string;
  description: string;
}

export interface PenaltyQueryParams {
  page?: number;
  per_page?: number;
  sort?: string;
  order?: "asc" | "desc";
  search?: string;
  organization_id?: string;
  invoice_id?: string;
}
