// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/supplier/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// SupplierRepositoryImpl implements SupplierRepository using PostgreSQL.
type SupplierRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewSupplierRepositoryImpl creates a new SupplierRepositoryImpl.
func NewSupplierRepositoryImpl(db *pgxpool.Pool) *SupplierRepositoryImpl {
	return &SupplierRepositoryImpl{db: db}
}

// Ensure SupplierRepositoryImpl implements domain repository interface.
var _ SupplierRepository = (*SupplierRepositoryImpl)(nil)

func (r *SupplierRepositoryImpl) Save(ctx context.Context, e *entity.Supplier) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO vendors (organization_id, name, contact_person, phone, service_type)
			VALUES ($1, $2, $3, $4, $5)
			RETURNING id`,
			e.OrganizationId, e.Name, e.ContactPerson, e.Phone, e.ServiceType,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE vendors
		SET    organization_id=$1, name=$2, contact_person=$3, phone=$4, service_type=$5
		WHERE  id=$6 AND deleted_at IS NULL`,
		e.OrganizationId, e.Name, e.ContactPerson, e.Phone, e.ServiceType, e.Id,
	)
	return err
}

func (r *SupplierRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Supplier, error) {
	e := &entity.Supplier{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, name, contact_person, phone, service_type, deleted_at
		FROM   vendors
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.Name, &e.ContactPerson, &e.Phone, &e.ServiceType, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("supplier repository: find by id: %w", err)
	}
	return e, nil
}

func (r *SupplierRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Supplier, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, name, contact_person, phone, service_type, deleted_at
		FROM   vendors
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("supplier repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Supplier
	for rows.Next() {
		e := &entity.Supplier{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.Name, &e.ContactPerson, &e.Phone, &e.ServiceType, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *SupplierRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE vendors SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
