// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/supplier/entity"
)

// SupplierRepository is the contract for persisting Supplier aggregates.
type SupplierRepository interface {
	// Save persists a Supplier entity.
	Save(ctx context.Context, e *entity.Supplier) error

	// FindByID retrieves a Supplier by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Supplier, error)

	// FindAll retrieves a paginated list of Supplier entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Supplier, error)

	// Delete removes a Supplier by its primary key.
	Delete(ctx context.Context, id string) error
}
