// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Asset,
  AssetListResponse,
  CreateAssetRequest,
  UpdateAssetRequest,
  AssetQueryParams,
} from "../types";

const BASE_PATH = "/assets";
export async function fetchAssets(params?: AssetQueryParams): Promise<AssetListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: AssetListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchAssetById(id: string): Promise<Asset> {
  const res = await api.get<{ success: boolean; data: Asset }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createAsset(data: CreateAssetRequest): Promise<Asset> {
  const res = await api.post<{ success: boolean; data: Asset }>(BASE_PATH, data);
  return res.data;
}
export async function updateAsset(id: string, data: UpdateAssetRequest): Promise<Asset> {
  const res = await api.put<{ success: boolean; data: Asset }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteAsset(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
