// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateRoomType } from "../hooks";
import { RoomTypeForm } from "../components/RoomTypeForm";
import type { CreateRoomTypeFormData } from "../schema";

export function RoomTypeCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateRoomType();

  const handleSubmit = (data: CreateRoomTypeFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/roomtype"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New RoomType</h1>
      <RoomTypeForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
