// Code generated by epmp-sdk. DO NOT EDIT.

export interface Room {
  organization_id: string;
  id: string;
  name: string;
  floor: number;
  capacity: number;
  price: number;
  is_available: boolean;
  property_id: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface RoomListResponse {
  data: Room[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreateRoomRequest {
  organization_id: string;
  name: string;
  floor: number;
  capacity: number;
  price: number;
  is_available: boolean;
  property_id: string;
}

export interface UpdateRoomRequest {
  organization_id: string;
  name: string;
  floor: number;
  capacity: number;
  price: number;
  is_available: boolean;
  property_id: string;
}

export interface RoomQueryParams {
  page?: number;
  per_page?: number;
  sort?: string;
  order?: "asc" | "desc";
  search?: string;
  organization_id?: string;
  name?: string;
}
