// Code generated by epmp-sdk. DO NOT EDIT.

package dto

import "time"

// CreateBedRequest is the DTO for creating a Bed.
type CreateBedRequest struct {
	OrganizationId string `json:"organization_id"`
	RoomId string `json:"room_id"`
	Name string `json:"name"`
	Status string `json:"status"`
}

// UpdateBedRequest is the DTO for updating a Bed.
type UpdateBedRequest struct {
	OrganizationId string `json:"organization_id"`
	RoomId string `json:"room_id"`
	Name string `json:"name"`
	Status string `json:"status"`
}

// BedResponse is the DTO for returning a Bed.
type BedResponse struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	RoomId string `json:"room_id"`
	Name string `json:"name"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// BedListResponse is the DTO for a paginated list of Bed.
type BedListResponse struct {
	Data       []BedResponse `json:"data"`
	Total      int64               `json:"total"`
	Page       int                 `json:"page"`
	PerPage    int                 `json:"per_page"`
	TotalPages int                 `json:"total_pages"`
}
