// Code generated by epmp-sdk. DO NOT EDIT.

package entity

import "time"

// Supplier is the domain entity for supplier.
type Supplier struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	Name string `json:"name"`
	ContactPerson string `json:"contact_person"`
	Phone string `json:"phone"`
	ServiceType string `json:"service_type"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewSupplier creates a new Supplier instance.
func NewSupplier() *Supplier {
	return &Supplier{}
}
