// Code generated by epmp-sdk. DO NOT EDIT.

package http

import (
	"strconv"

	"github.com/epmp/backend/internal/modules/billing/dto"
	"github.com/epmp/backend/internal/modules/billing/service"
	"github.com/epmp/backend/internal/pkg/response"

	"github.com/labstack/echo/v4"
)

// InvoiceHandler handles HTTP requests for Invoice resources.
type InvoiceHandler struct {
	svc *service.InvoiceService
}

// NewInvoiceHandler creates a new InvoiceHandler.
func NewInvoiceHandler(svc *service.InvoiceService) *InvoiceHandler {
	return &InvoiceHandler{svc: svc}
}

func (h *InvoiceHandler) Create(c echo.Context) error {
	var req dto.CreateInvoiceRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Create(c.Request().Context(), &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.Created(c, result)
}

func (h *InvoiceHandler) GetByID(c echo.Context) error {
	id := c.Param("id")

	result, err := h.svc.GetByID(c.Request().Context(), id)
	if err != nil {
		return response.NotFound(c, "Invoice not found")
	}

	return response.OK(c, result)
}

func (h *InvoiceHandler) List(c echo.Context) error {
	page, _ := strconv.Atoi(c.QueryParam("page"))
	if page == 0 {
		page = 1
	}
	perPage, _ := strconv.Atoi(c.QueryParam("per_page"))
	if perPage == 0 {
		perPage = 20
	}

	result, err := h.svc.List(c.Request().Context(), page, perPage)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *InvoiceHandler) Update(c echo.Context) error {
	id := c.Param("id")

	var req dto.UpdateInvoiceRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Update(c.Request().Context(), id, &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *InvoiceHandler) Delete(c echo.Context) error {
	id := c.Param("id")

	if err := h.svc.Delete(c.Request().Context(), id); err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.NoContent(c)
}
