// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateAsset } from "../hooks";
import { AssetForm } from "../components/AssetForm";
import type { CreateAssetFormData } from "../schema";

export function AssetCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateAsset();

  const handleSubmit = (data: CreateAssetFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/asset"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New Asset</h1>
      <AssetForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
