// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const propertySchema = z.object({
  id: z.z.string(),
  name: z.z.string().max(255).nonempty(),
  description: z.z.string().optional(),
  address: z.z.string().optional(),
  property_type: z.z.string().nonempty().enum(["boarding_house", "apartment", "villa", "warehouse"]),
  is_active: z.z.boolean().nonempty(),
});

export const createPropertySchema = propertySchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export const updatePropertySchema = createPropertySchema.partial();

export type PropertyFormData = z.infer<typeof propertySchema>;
export type CreatePropertyFormData = z.infer<typeof createPropertySchema>;
export type UpdatePropertyFormData = z.infer<typeof updatePropertySchema>;
