// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const propertySchema = z.object({
  organization_id: z.string(),
  id: z.string(),
  name: z.string().max(255),
  description: z.string().optional(),
  address: z.string().optional(),
  property_type: z.enum(["boarding_house", "apartment", "villa", "warehouse"]),
  is_active: z.boolean(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createPropertySchema = propertySchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export const updatePropertySchema = createPropertySchema.partial();

export type PropertyFormData = z.infer<typeof propertySchema>;
export type CreatePropertyFormData = z.infer<typeof createPropertySchema>;
export type UpdatePropertyFormData = z.infer<typeof updatePropertySchema>;
