// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/billing/entity"
)

// InvoiceRepository is the contract for persisting Invoice aggregates.
type InvoiceRepository interface {
	// Save persists a Invoice entity.
	Save(ctx context.Context, e *entity.Invoice) error

	// FindByID retrieves a Invoice by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Invoice, error)

	// FindAll retrieves a paginated list of Invoice entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Invoice, error)

	// Delete removes a Invoice by its primary key.
	Delete(ctx context.Context, id string) error
}
