// Code generated by epmp-sdk. DO NOT EDIT.

package entity

import "time"

// Zone is the domain entity for zone.
type Zone struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	BuildingId string `json:"building_id"`
	Floor int `json:"floor"`
	Name string `json:"name"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewZone creates a new Zone instance.
func NewZone() *Zone {
	return &Zone{}
}
