// Code generated by epmp-sdk. DO NOT EDIT.

export interface Invoice {
  organization_id: string;
  id: string;
  contract_id: string;
  tenant_id: string;
  amount: number;
  currency: string;
  status: string;
  due_date: string;
  paid_date?: string;
  payment_method?: string;
  notes?: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface InvoiceListResponse {
  data: Invoice[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreateInvoiceRequest {
  contract_id: string;
  tenant_id: string;
  amount: number;
  currency?: string;
  status: string;
  due_date: string;
  paid_date?: string;
  payment_method?: string;
  notes?: string;
}

export interface UpdateInvoiceRequest {
  contract_id: string;
  tenant_id: string;
  amount: number;
  currency?: string;
  status: string;
  due_date: string;
  paid_date?: string;
  payment_method?: string;
  notes?: string;
}

export interface InvoiceQueryParams {
  page?: number;
  per_page?: number;
  search?: string;
  contract_id?: string;
  tenant_id?: string;
}
