// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/refund/entity"
)

// RefundRepository is the contract for persisting Refund aggregates.
type RefundRepository interface {
	// Save persists a Refund entity.
	Save(ctx context.Context, e *entity.Refund) error

	// FindByID retrieves a Refund by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Refund, error)

	// FindAll retrieves a paginated list of Refund entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Refund, error)

	// Delete removes a Refund by its primary key.
	Delete(ctx context.Context, id string) error
}
