// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/refund/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// RefundRepositoryImpl implements RefundRepository using PostgreSQL.
type RefundRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewRefundRepositoryImpl creates a new RefundRepositoryImpl.
func NewRefundRepositoryImpl(db *pgxpool.Pool) *RefundRepositoryImpl {
	return &RefundRepositoryImpl{db: db}
}

// Ensure RefundRepositoryImpl implements domain repository interface.
var _ RefundRepository = (*RefundRepositoryImpl)(nil)

func (r *RefundRepositoryImpl) Save(ctx context.Context, e *entity.Refund) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO refunds (organization_id, payment_id, tenant_id, amount, status, refund_date, reason)
			VALUES ($1, $2, $3, $4, $5, $6, $7)
			RETURNING id`,
			e.OrganizationId, e.PaymentId, e.TenantId, e.Amount, e.Status, e.RefundDate, e.Reason,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE refunds
		SET    organization_id=$1, payment_id=$2, tenant_id=$3, amount=$4, status=$5, refund_date=$6, reason=$7
		WHERE  id=$8 AND deleted_at IS NULL`,
		e.OrganizationId, e.PaymentId, e.TenantId, e.Amount, e.Status, e.RefundDate, e.Reason, e.Id,
	)
	return err
}

func (r *RefundRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Refund, error) {
	e := &entity.Refund{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, payment_id, tenant_id, amount, status, refund_date, reason, deleted_at
		FROM   refunds
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.PaymentId, &e.TenantId, &e.Amount, &e.Status, &e.RefundDate, &e.Reason, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("refund repository: find by id: %w", err)
	}
	return e, nil
}

func (r *RefundRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Refund, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, payment_id, tenant_id, amount, status, refund_date, reason, deleted_at
		FROM   refunds
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("refund repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Refund
	for rows.Next() {
		e := &entity.Refund{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.PaymentId, &e.TenantId, &e.Amount, &e.Status, &e.RefundDate, &e.Reason, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *RefundRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE refunds SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
