// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useQuery,
  useMutation,
  useQueryClient,
} from "@tanstack/react-query";
import {
  fetchTenantIdentitys,
  fetchTenantIdentityById,
  createTenantIdentity,
  updateTenantIdentity,
  deleteTenantIdentity,
} from "../api";
import type {
  TenantIdentityQueryParams,
  CreateTenantIdentityRequest,
  UpdateTenantIdentityRequest,
} from "../types";

const QUERY_KEY = "tenantIdentitys";
export function useTenantIdentitys(params?: TenantIdentityQueryParams) {
  return useQuery({
    queryKey: [QUERY_KEY, params],
    queryFn: () => fetchTenantIdentitys(params),
  });
}
export function useTenantIdentity(id: string | undefined) {
  return useQuery({
    queryKey: [QUERY_KEY, id],
    queryFn: () => fetchTenantIdentityById(id!),
    enabled: !!id,
  });
}
export function useCreateTenantIdentity() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateTenantIdentityRequest) => createTenantIdentity(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useUpdateTenantIdentity() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateTenantIdentityRequest }) =>
      updateTenantIdentity(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useDeleteTenantIdentity() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteTenantIdentity(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
