// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Room,
  RoomListResponse,
  CreateRoomRequest,
  UpdateRoomRequest,
  RoomQueryParams,
} from "../types";

const BASE_PATH = "/api/rooms";
export async function fetchRooms(params?: RoomQueryParams): Promise<RoomListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<RoomListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchRoomById(id: string): Promise<Room> {
  return api.get<Room>(`${BASE_PATH}/${id}`);
}
export async function createRoom(data: CreateRoomRequest): Promise<Room> {
  return api.post<Room>(BASE_PATH, data);
}
export async function updateRoom(id: string, data: UpdateRoomRequest): Promise<Room> {
  return api.put<Room>(`${BASE_PATH}/${id}`, data);
}
export async function deleteRoom(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
