// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  createColumnHelper,
} from "@tanstack/react-table";
import type { AssetInspection } from "../types";
import { useAssets } from "../../asset/hooks";
import { formatDate } from "@/utils/date";

const columnHelper = createColumnHelper<AssetInspection>();


interface AssetInspectionTableProps {
  data: AssetInspection[];
  onRowClick?: (row: AssetInspection) => void;
}

export function AssetInspectionTable({ data, onRowClick }: AssetInspectionTableProps) {
  const { data: assetsData } = useAssets({ per_page: 100 });
  const assetsMap = new Map(
    (Array.isArray(assetsData?.data) ? assetsData.data : Array.isArray(assetsData) ? assetsData : [])
      .map((item: any) => [item.id, item.name])
  );

  const columns = [
    columnHelper.accessor("asset_id", {
      header: "Asset",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        return assetsMap.get(id) || <span className="text-slate-400 font-mono text-xs">#{id.slice(0, 8)}</span>;
      },
    }),
    columnHelper.accessor("inspection_date", {
      header: "Inspection Date",
      cell: (info) => <span className="text-slate-700">{formatDate(info.getValue() as string)}</span>,
    }),
    columnHelper.accessor("condition", {
      header: "Kondisi",
      cell: (info) => {
        const val = (info.getValue() as string) || "Good";
        const isGood = val.toLowerCase() === "good" || val.toLowerCase() === "baik";
        return (
          <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
            isGood ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'
          }`}>
            {val}
          </span>
        );
      },
    }),
    columnHelper.accessor("notes", {
      header: "Notes",
      cell: (info) => info.getValue(),
    }),
  ];

  const table = useReactTable({
    data: data || [],
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  return (
    <div className="rounded-xl border border-slate-200 bg-white overflow-hidden shadow-sm">
      <table className="w-full text-sm text-left">
        <thead className="border-b border-slate-200 bg-slate-50/75 text-slate-600 font-semibold">
          {table.getHeaderGroups().map((headerGroup) => (
            <tr key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <th key={header.id} className="px-5 py-3.5">
                  {flexRender(
                    header.column.columnDef.header,
                    header.getContext()
                  )}
                </th>
              ))}
            </tr>
          ))}
        </thead>
        <tbody className="divide-y divide-slate-100">
          {table.getRowModel().rows.map((row) => (
            <tr
              key={row.id}
              className="hover:bg-orange/5 cursor-pointer transition-colors"
              onClick={() => onRowClick?.(row.original)}
            >
              {row.getVisibleCells().map((cell) => (
                <td key={cell.id} className="px-5 py-4">
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </td>
              ))}
            </tr>
          ))}
          {table.getRowModel().rows.length === 0 && (
            <tr>
              <td colSpan={columns.length} className="px-5 py-12 text-center text-slate-400">
                No data found.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}
