// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateTenant } from "../hooks";
import { TenantForm } from "../components/TenantForm";
import type { CreateTenantFormData } from "../schema";

export function TenantCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateTenant();

  const handleSubmit = (data: CreateTenantFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/tenant"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New Tenant</h1>
      <TenantForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
