// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Technician,
  TechnicianListResponse,
  CreateTechnicianRequest,
  UpdateTechnicianRequest,
  TechnicianQueryParams,
} from "../types";

const BASE_PATH = "/api/technicians";
export async function fetchTechnicians(params?: TechnicianQueryParams): Promise<TechnicianListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<TechnicianListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchTechnicianById(id: string): Promise<Technician> {
  return api.get<Technician>(`${BASE_PATH}/${id}`);
}
export async function createTechnician(data: CreateTechnicianRequest): Promise<Technician> {
  return api.post<Technician>(BASE_PATH, data);
}
export async function updateTechnician(id: string, data: UpdateTechnicianRequest): Promise<Technician> {
  return api.put<Technician>(`${BASE_PATH}/${id}`, data);
}
export async function deleteTechnician(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
