// Code generated by epmp-sdk. DO NOT EDIT.

package entity

import "time"

// Tenant is the domain entity for tenant.
type Tenant struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	FullName string `json:"full_name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
	IdentityNumber string `json:"identity_number"`
	IsActive bool `json:"is_active"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewTenant creates a new Tenant instance.
func NewTenant() *Tenant {
	return &Tenant{}
}
