// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  TenantIdentity,
  TenantIdentityListResponse,
  CreateTenantIdentityRequest,
  UpdateTenantIdentityRequest,
  TenantIdentityQueryParams,
} from "../types";

const BASE_PATH = "/tenant_identities";
export async function fetchTenantIdentitys(params?: TenantIdentityQueryParams): Promise<TenantIdentityListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: TenantIdentityListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchTenantIdentityById(id: string): Promise<TenantIdentity> {
  const res = await api.get<{ success: boolean; data: TenantIdentity }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createTenantIdentity(data: CreateTenantIdentityRequest): Promise<TenantIdentity> {
  const res = await api.post<{ success: boolean; data: TenantIdentity }>(BASE_PATH, data);
  return res.data;
}
export async function updateTenantIdentity(id: string, data: UpdateTenantIdentityRequest): Promise<TenantIdentity> {
  const res = await api.put<{ success: boolean; data: TenantIdentity }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteTenantIdentity(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
