// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { usePayment, useDeletePayment } from "../hooks";

export function PaymentDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = usePayment(id);
  const deleteMutation = useDeletePayment();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this payment?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/dashboard/payments"),
    });
  };

  if (isLoading) return <div className="text-center py-12 text-slate-400">Loading...</div>;
  if (!data) return <div className="text-center py-12 text-slate-400">Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Payment Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/dashboard/payments")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/dashboard/payments/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2 bg-white rounded-xl border border-slate-200 shadow-sm p-6">
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">OrganizationId</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.organization_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Id</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">InvoiceId</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.invoice_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">TenantId</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.tenant_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Amount</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.amount ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">PaymentDate</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.payment_date ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">PaymentMethod</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.payment_method ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Status</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.status ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">ReferenceNumber</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.reference_number ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
