// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Tenant,
  TenantListResponse,
  CreateTenantRequest,
  UpdateTenantRequest,
  TenantQueryParams,
} from "../types";

const BASE_PATH = "/tenants";
export async function fetchTenants(params?: TenantQueryParams): Promise<TenantListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: TenantListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchTenantById(id: string): Promise<Tenant> {
  const res = await api.get<{ success: boolean; data: Tenant }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createTenant(data: CreateTenantRequest): Promise<Tenant> {
  const res = await api.post<{ success: boolean; data: Tenant }>(BASE_PATH, data);
  return res.data;
}
export async function updateTenant(id: string, data: UpdateTenantRequest): Promise<Tenant> {
  const res = await api.put<{ success: boolean; data: Tenant }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteTenant(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
