// Code generated by epmp-sdk. DO NOT EDIT.

export interface Reservation {
  organization_id: string;
  id: string;
  tenant_id: string;
  property_id: string;
  room_id: string;
  status: string;
  check_in_date: string;
  check_out_date?: string;
  booking_fee: number;
  notes?: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface ReservationListResponse {
  data: Reservation[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreateReservationRequest {
  organization_id: string;
  tenant_id: string;
  property_id: string;
  room_id: string;
  status: string;
  check_in_date: string;
  check_out_date?: string;
  booking_fee: number;
  notes?: string;
}

export interface UpdateReservationRequest {
  organization_id: string;
  tenant_id: string;
  property_id: string;
  room_id: string;
  status: string;
  check_in_date: string;
  check_out_date?: string;
  booking_fee: number;
  notes?: string;
}

export interface ReservationQueryParams {
  page?: number;
  per_page?: number;
  sort?: string;
  order?: "asc" | "desc";
  search?: string;
  organization_id?: string;
  tenant_id?: string;
  property_id?: string;
  room_id?: string;
}
