// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  createRoomTypeSchema,
  type CreateRoomTypeFormData,
} from "../schema";

interface RoomTypeFormProps {
  onSubmit: (data: CreateRoomTypeFormData) => void;
  defaultValues?: Partial<CreateRoomTypeFormData>;
  isSubmitting?: boolean;
}

export function RoomTypeForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: RoomTypeFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateRoomTypeFormData>({
    resolver: zodResolver(createRoomTypeSchema),
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      <div className="space-y-2">
        <Label htmlFor="name">Name</Label>
        <Input
          id="name"
          {...register("name")}
        />
        {errors.name && (
          <p className="text-xs text-red-600 mt-1">{errors.name.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="description">Description</Label>
        <Input
          id="description"
          {...register("description")}
        />
        {errors.description && (
          <p className="text-xs text-red-600 mt-1">{errors.description.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="base_price">Base Price (Rp)</Label>
        <Input
          id="base_price"
          type="number"
          step="any"
          min="0"
          placeholder="e.g. 500000"
          {...register("base_price", { valueAsNumber: true })}
        />
        <p className="text-xs text-slate-500">
          Template default rate for rooms assigned to this type. Can still be customized per room.
        </p>
        {errors.base_price && (
          <p className="text-xs text-red-600 mt-1">{errors.base_price.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting} className="bg-orange hover:bg-orange/90 text-white w-full sm:w-auto">
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
