// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  createReservationSchema,
  type CreateReservationFormData,
} from "../schema";

interface ReservationFormProps {
  onSubmit: (data: CreateReservationFormData) => void;
  defaultValues?: Partial<CreateReservationFormData>;
  isSubmitting?: boolean;
}

export function ReservationForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: ReservationFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateReservationFormData>({
    resolver: zodResolver(createReservationSchema),
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="tenant_id">TenantId</Label>
        <Input
          id="tenant_id"
          {...register("tenant_id")}
        />
        {errors.tenant_id && (
          <p className="text-sm text-red-500">{errors.tenant_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="property_id">PropertyId</Label>
        <Input
          id="property_id"
          {...register("property_id")}
        />
        {errors.property_id && (
          <p className="text-sm text-red-500">{errors.property_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="room_id">RoomId</Label>
        <Input
          id="room_id"
          {...register("room_id")}
        />
        {errors.room_id && (
          <p className="text-sm text-red-500">{errors.room_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="status">Status</Label>
        <Input
          id="status"
          {...register("status")}
        />
        {errors.status && (
          <p className="text-sm text-red-500">{errors.status.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="check_in_date">CheckInDate</Label>
        <Input
          id="check_in_date"
          {...register("check_in_date")}
        />
        {errors.check_in_date && (
          <p className="text-sm text-red-500">{errors.check_in_date.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="check_out_date">CheckOutDate</Label>
        <Input
          id="check_out_date"
          {...register("check_out_date")}
        />
        {errors.check_out_date && (
          <p className="text-sm text-red-500">{errors.check_out_date.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="booking_fee">BookingFee</Label>
        <Input
          id="booking_fee"
          {...register("booking_fee")}
        />
        {errors.booking_fee && (
          <p className="text-sm text-red-500">{errors.booking_fee.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="notes">Notes</Label>
        <Input
          id="notes"
          {...register("notes")}
        />
        {errors.notes && (
          <p className="text-sm text-red-500">{errors.notes.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting}>
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
