// Code generated by epmp-sdk. DO NOT EDIT.

package http

import (
	"strconv"

	"github.com/epmp/backend/internal/modules/asset/dto"
	"github.com/epmp/backend/internal/modules/asset/service"
	"github.com/epmp/backend/internal/pkg/response"

	"github.com/labstack/echo/v4"
)

// AssetHandler handles HTTP requests for Asset resources.
type AssetHandler struct {
	svc *service.AssetService
}

// NewAssetHandler creates a new AssetHandler.
func NewAssetHandler(svc *service.AssetService) *AssetHandler {
	return &AssetHandler{svc: svc}
}

func (h *AssetHandler) Create(c echo.Context) error {
	var req dto.CreateAssetRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Create(c.Request().Context(), &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.Created(c, result)
}

func (h *AssetHandler) GetByID(c echo.Context) error {
	id := c.Param("id")

	result, err := h.svc.GetByID(c.Request().Context(), id)
	if err != nil {
		return response.NotFound(c, "Asset not found")
	}

	return response.OK(c, result)
}

func (h *AssetHandler) List(c echo.Context) error {
	page, _ := strconv.Atoi(c.QueryParam("page"))
	if page == 0 {
		page = 1
	}
	perPage, _ := strconv.Atoi(c.QueryParam("per_page"))
	if perPage == 0 {
		perPage = 20
	}

	result, err := h.svc.List(c.Request().Context(), page, perPage)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *AssetHandler) Update(c echo.Context) error {
	id := c.Param("id")

	var req dto.UpdateAssetRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Update(c.Request().Context(), id, &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *AssetHandler) Delete(c echo.Context) error {
	id := c.Param("id")

	if err := h.svc.Delete(c.Request().Context(), id); err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.NoContent(c)
}
