// Code generated by epmp-sdk. DO NOT EDIT.

package http

import (
	"strconv"

	"github.com/epmp/backend/internal/modules/roomtype/dto"
	"github.com/epmp/backend/internal/modules/roomtype/service"
	"github.com/epmp/backend/internal/pkg/response"

	"github.com/labstack/echo/v4"
)

// RoomTypeHandler handles HTTP requests for RoomType resources.
type RoomTypeHandler struct {
	svc *service.RoomTypeService
}

// NewRoomTypeHandler creates a new RoomTypeHandler.
func NewRoomTypeHandler(svc *service.RoomTypeService) *RoomTypeHandler {
	return &RoomTypeHandler{svc: svc}
}

func (h *RoomTypeHandler) Create(c echo.Context) error {
	var req dto.CreateRoomTypeRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Create(c.Request().Context(), &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.Created(c, result)
}

func (h *RoomTypeHandler) GetByID(c echo.Context) error {
	id := c.Param("id")

	result, err := h.svc.GetByID(c.Request().Context(), id)
	if err != nil {
		return response.NotFound(c, "RoomType not found")
	}

	return response.OK(c, result)
}

func (h *RoomTypeHandler) List(c echo.Context) error {
	page, _ := strconv.Atoi(c.QueryParam("page"))
	if page == 0 {
		page = 1
	}
	perPage, _ := strconv.Atoi(c.QueryParam("per_page"))
	if perPage == 0 {
		perPage = 20
	}

	result, err := h.svc.List(c.Request().Context(), page, perPage)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *RoomTypeHandler) Update(c echo.Context) error {
	id := c.Param("id")

	var req dto.UpdateRoomTypeRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Update(c.Request().Context(), id, &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *RoomTypeHandler) Delete(c echo.Context) error {
	id := c.Param("id")

	if err := h.svc.Delete(c.Request().Context(), id); err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.NoContent(c)
}
