// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  AssetInspection,
  AssetInspectionListResponse,
  CreateAssetInspectionRequest,
  UpdateAssetInspectionRequest,
  AssetInspectionQueryParams,
} from "../types";

const BASE_PATH = "/api/asset_inspections";
export async function fetchAssetInspections(params?: AssetInspectionQueryParams): Promise<AssetInspectionListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<AssetInspectionListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchAssetInspectionById(id: string): Promise<AssetInspection> {
  return api.get<AssetInspection>(`${BASE_PATH}/${id}`);
}
export async function createAssetInspection(data: CreateAssetInspectionRequest): Promise<AssetInspection> {
  return api.post<AssetInspection>(BASE_PATH, data);
}
export async function updateAssetInspection(id: string, data: UpdateAssetInspectionRequest): Promise<AssetInspection> {
  return api.put<AssetInspection>(`${BASE_PATH}/${id}`, data);
}
export async function deleteAssetInspection(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
