// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Reservation,
  ReservationListResponse,
  CreateReservationRequest,
  UpdateReservationRequest,
  ReservationQueryParams,
} from "../types";

const BASE_PATH = "/api/reservations";
export async function fetchReservations(params?: ReservationQueryParams): Promise<ReservationListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<ReservationListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchReservationById(id: string): Promise<Reservation> {
  return api.get<Reservation>(`${BASE_PATH}/${id}`);
}
export async function createReservation(data: CreateReservationRequest): Promise<Reservation> {
  return api.post<Reservation>(BASE_PATH, data);
}
export async function updateReservation(id: string, data: UpdateReservationRequest): Promise<Reservation> {
  return api.put<Reservation>(`${BASE_PATH}/${id}`, data);
}
export async function deleteReservation(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
