// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  createColumnHelper,
} from "@tanstack/react-table";
import type { Refund } from "../types";
import { usePayments } from "../../payment/hooks";
import { useTenants } from "../../tenant/hooks";

const columnHelper = createColumnHelper<Refund>();


interface RefundTableProps {
  data: Refund[];
  onRowClick?: (row: Refund) => void;
}

export function RefundTable({ data, onRowClick }: RefundTableProps) {
  const { data: paymentsData } = usePayments({ per_page: 100 });
  const { data: tenantsData } = useTenants({ per_page: 100 });
  const paymentsMap = new Map(
    (Array.isArray(paymentsData?.data) ? paymentsData.data : Array.isArray(paymentsData) ? paymentsData : [])
      .map((item: any) => [item.id, `#` + item.id.slice(0, 8)])
  );
  const tenantsMap = new Map(
    (Array.isArray(tenantsData?.data) ? tenantsData.data : Array.isArray(tenantsData) ? tenantsData : [])
      .map((item: any) => [item.id, item.full_name])
  );

  const columns = [
    columnHelper.accessor("payment_id", {
      header: "Payment",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        return paymentsMap.get(id) || <span className="text-slate-400 font-mono text-xs">#{id.slice(0, 8)}</span>;
      },
    }),
    columnHelper.accessor("tenant_id", {
      header: "Tenant",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        return tenantsMap.get(id) || <span className="text-slate-400 font-mono text-xs">#{id.slice(0, 8)}</span>;
      },
    }),
    columnHelper.accessor("amount", {
      header: "Amount",
      cell: (info) => info.getValue(),
    }),
    columnHelper.accessor("status", {
      header: "Status",
      cell: (info) => info.getValue(),
    }),
    columnHelper.accessor("refund_date", {
      header: "RefundDate",
      cell: (info) => info.getValue(),
    }),
    columnHelper.accessor("reason", {
      header: "Reason",
      cell: (info) => info.getValue(),
    }),
  ];

  const table = useReactTable({
    data: data || [],
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  return (
    <div className="rounded-xl border border-slate-200 bg-white overflow-hidden shadow-sm">
      <table className="w-full text-sm text-left">
        <thead className="border-b border-slate-200 bg-slate-50/75 text-slate-600 font-semibold">
          {table.getHeaderGroups().map((headerGroup) => (
            <tr key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <th key={header.id} className="px-5 py-3.5">
                  {flexRender(
                    header.column.columnDef.header,
                    header.getContext()
                  )}
                </th>
              ))}
            </tr>
          ))}
        </thead>
        <tbody className="divide-y divide-slate-100">
          {table.getRowModel().rows.map((row) => (
            <tr
              key={row.id}
              className="hover:bg-orange/5 cursor-pointer transition-colors"
              onClick={() => onRowClick?.(row.original)}
            >
              {row.getVisibleCells().map((cell) => (
                <td key={cell.id} className="px-5 py-4">
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </td>
              ))}
            </tr>
          ))}
          {table.getRowModel().rows.length === 0 && (
            <tr>
              <td colSpan={columns.length} className="px-5 py-12 text-center text-slate-400">
                No data found.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}
