// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useTechnician, useDeleteTechnician } from "../hooks";

export function TechnicianDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useTechnician(id);
  const deleteMutation = useDeleteTechnician();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this technician?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/dashboard/technicians"),
    });
  };

  if (isLoading) return <div className="text-center py-12 text-slate-400">Loading...</div>;
  if (!data) return <div className="text-center py-12 text-slate-400">Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Technician Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/dashboard/technicians")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/dashboard/technicians/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2 bg-white rounded-xl border border-slate-200 shadow-sm p-6">
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">OrganizationId</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.organization_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Id</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Name</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.name ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Phone</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.phone ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Specialty</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.specialty ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
