// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateTechnician } from "../hooks";
import { TechnicianForm } from "../components/TechnicianForm";
import type { CreateTechnicianFormData } from "../schema";

export function TechnicianCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateTechnician();

  const handleSubmit = (data: CreateTechnicianFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/technician"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New Technician</h1>
      <TechnicianForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
