// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useQuery,
  useMutation,
  useQueryClient,
} from "@tanstack/react-query";
import {
  fetchCharges,
  fetchChargeById,
  createCharge,
  updateCharge,
  deleteCharge,
} from "../api";
import type {
  ChargeQueryParams,
  CreateChargeRequest,
  UpdateChargeRequest,
} from "../types";

const QUERY_KEY = "charges";
export function useCharges(params?: ChargeQueryParams) {
  return useQuery({
    queryKey: [QUERY_KEY, params],
    queryFn: () => fetchCharges(params),
  });
}
export function useCharge(id: string | undefined) {
  return useQuery({
    queryKey: [QUERY_KEY, id],
    queryFn: () => fetchChargeById(id!),
    enabled: !!id,
  });
}
export function useCreateCharge() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateChargeRequest) => createCharge(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useUpdateCharge() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateChargeRequest }) =>
      updateCharge(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useDeleteCharge() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteCharge(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
