// Code generated by epmp-sdk. DO NOT EDIT.

package service

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/property/application/dto"
	"github.com/epmp/backend/internal/modules/property/domain/entity"
	"github.com/epmp/backend/internal/modules/property/domain/repository"
)

// PropertyService implements the application layer for Property.
type PropertyService struct {
	repo repository.PropertyRepository
}

// NewPropertyService creates a new PropertyService.
func NewPropertyService(repo repository.PropertyRepository) *PropertyService {
	return &PropertyService{repo: repo}
}

func (s *PropertyService) Create(ctx context.Context, req *dto.CreatePropertyRequest) (*dto.PropertyResponse, error) {
	e := entity.NewProperty()
	e.Name = req.Name
	e.Description = req.Description
	e.Address = req.Address
	e.PropertyType = req.PropertyType
	e.IsActive = req.IsActive

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("property service: create: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *PropertyService) GetByID(ctx context.Context, id string) (*dto.PropertyResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("property service: get by id: %w", err)
	}
	return s.toResponse(e), nil
}

func (s *PropertyService) List(ctx context.Context, page, perPage int) (*dto.PropertyListResponse, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 {
		perPage = 20
	}
	offset := (page - 1) * perPage

	items, err := s.repo.FindAll(ctx, perPage, offset)
	if err != nil {
		return nil, fmt.Errorf("property service: list: %w", err)
	}

	data := make([]dto.PropertyResponse, 0, len(items))
	for _, e := range items {
		data = append(data, *s.toResponse(e))
	}

	return &dto.PropertyListResponse{
		Data:    data,
		Page:    page,
		PerPage: perPage,
	}, nil
}

func (s *PropertyService) Update(ctx context.Context, id string, req *dto.UpdatePropertyRequest) (*dto.PropertyResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("property service: update: find: %w", err)
	}
	e.Name = req.Name
	e.Description = req.Description
	e.Address = req.Address
	e.PropertyType = req.PropertyType
	e.IsActive = req.IsActive

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("property service: update: save: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *PropertyService) Delete(ctx context.Context, id string) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("property service: delete: %w", err)
	}
	return nil
}

func (s *PropertyService) toResponse(e *entity.Property) *dto.PropertyResponse {
	return &dto.PropertyResponse{
		Id: e.Id,
		Name: e.Name,
		Description: e.Description,
		Address: e.Address,
		PropertyType: e.PropertyType,
		IsActive: e.IsActive,
	}
}
