// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  createBedSchema,
  type CreateBedFormData,
} from "../schema";

interface BedFormProps {
  onSubmit: (data: CreateBedFormData) => void;
  defaultValues?: Partial<CreateBedFormData>;
  isSubmitting?: boolean;
}

export function BedForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: BedFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateBedFormData>({
    resolver: zodResolver(createBedSchema),
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="organization_id">OrganizationId</Label>
        <Input
          id="organization_id"
          {...register("organization_id")}
        />
        {errors.organization_id && (
          <p className="text-sm text-red-500">{errors.organization_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="room_id">RoomId</Label>
        <Input
          id="room_id"
          {...register("room_id")}
        />
        {errors.room_id && (
          <p className="text-sm text-red-500">{errors.room_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="name">Name</Label>
        <Input
          id="name"
          {...register("name")}
        />
        {errors.name && (
          <p className="text-sm text-red-500">{errors.name.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="status">Status</Label>
        <Input
          id="status"
          {...register("status")}
        />
        {errors.status && (
          <p className="text-sm text-red-500">{errors.status.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting}>
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
