// Code generated by epmp-sdk. DO NOT EDIT.

package service

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/payment/dto"
	"github.com/epmp/backend/internal/modules/payment/entity"
	"github.com/epmp/backend/internal/modules/payment/repository"
)

// PaymentService implements the application layer for Payment.
type PaymentService struct {
	repo repository.PaymentRepository
}

// NewPaymentService creates a new PaymentService.
func NewPaymentService(repo repository.PaymentRepository) *PaymentService {
	return &PaymentService{repo: repo}
}

func (s *PaymentService) Create(ctx context.Context, req *dto.CreatePaymentRequest) (*dto.PaymentResponse, error) {
	e := entity.NewPayment()
	e.OrganizationId = req.OrganizationId
	e.InvoiceId = req.InvoiceId
	e.TenantId = req.TenantId
	e.Amount = req.Amount
	e.PaymentDate = req.PaymentDate
	e.PaymentMethod = req.PaymentMethod
	e.Status = req.Status
	e.ReferenceNumber = req.ReferenceNumber

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("payment service: create: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *PaymentService) GetByID(ctx context.Context, id string) (*dto.PaymentResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("payment service: get by id: %w", err)
	}
	return s.toResponse(e), nil
}

func (s *PaymentService) List(ctx context.Context, page, perPage int) (*dto.PaymentListResponse, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 {
		perPage = 20
	}
	offset := (page - 1) * perPage

	items, err := s.repo.FindAll(ctx, perPage, offset)
	if err != nil {
		return nil, fmt.Errorf("payment service: list: %w", err)
	}

	data := make([]dto.PaymentResponse, 0, len(items))
	for _, e := range items {
		data = append(data, *s.toResponse(e))
	}

	return &dto.PaymentListResponse{
		Data:    data,
		Page:    page,
		PerPage: perPage,
	}, nil
}

func (s *PaymentService) Update(ctx context.Context, id string, req *dto.UpdatePaymentRequest) (*dto.PaymentResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("payment service: update: find: %w", err)
	}
	e.OrganizationId = req.OrganizationId
	e.InvoiceId = req.InvoiceId
	e.TenantId = req.TenantId
	e.Amount = req.Amount
	e.PaymentDate = req.PaymentDate
	e.PaymentMethod = req.PaymentMethod
	e.Status = req.Status
	e.ReferenceNumber = req.ReferenceNumber

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("payment service: update: save: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *PaymentService) Delete(ctx context.Context, id string) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("payment service: delete: %w", err)
	}
	return nil
}

func (s *PaymentService) toResponse(e *entity.Payment) *dto.PaymentResponse {
	return &dto.PaymentResponse{
		OrganizationId: e.OrganizationId,
		Id: e.Id,
		InvoiceId: e.InvoiceId,
		TenantId: e.TenantId,
		Amount: e.Amount,
		PaymentDate: e.PaymentDate,
		PaymentMethod: e.PaymentMethod,
		Status: e.Status,
		ReferenceNumber: e.ReferenceNumber,
	}
}
