// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Deposit,
  DepositListResponse,
  CreateDepositRequest,
  UpdateDepositRequest,
  DepositQueryParams,
} from "../types";

const BASE_PATH = "/deposits";
export async function fetchDeposits(params?: DepositQueryParams): Promise<DepositListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: DepositListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchDepositById(id: string): Promise<Deposit> {
  const res = await api.get<{ success: boolean; data: Deposit }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createDeposit(data: CreateDepositRequest): Promise<Deposit> {
  const res = await api.post<{ success: boolean; data: Deposit }>(BASE_PATH, data);
  return res.data;
}
export async function updateDeposit(id: string, data: UpdateDepositRequest): Promise<Deposit> {
  const res = await api.put<{ success: boolean; data: Deposit }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteDeposit(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
