// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateRoom } from "../hooks";
import { RoomForm } from "../components/RoomForm";
import type { CreateRoomFormData } from "../schema";

export function RoomCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateRoom();

  const handleSubmit = (data: CreateRoomFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/room"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New Room</h1>
      <RoomForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
