// Code generated by epmp-sdk. DO NOT EDIT.

package room

import (
	"github.com/epmp/backend/internal/modules/room/application/service"
	domainrepo "github.com/epmp/backend/internal/modules/room/domain/repository"
	"github.com/epmp/backend/internal/modules/room/infrastructure/repository"
	"github.com/epmp/backend/internal/modules/room/interfaces/http"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all Room dependencies.
type Module struct {
	Handler *http.RoomHandler
}

// NewModule creates and wires all Room dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo domainrepo.RoomRepository = repository.NewRoomRepositoryImpl(db)
	svc := service.NewRoomService(repo)
	handler := http.NewRoomHandler(svc)

	log.Info().Str("module", "room").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all Room routes under the given API group.
// Call as: roomMod.RegisterRoutes(v1) where v1 = e.Group("/api/v1").
func (m *Module) RegisterRoutes(v1 *echo.Group) {
	g := v1.Group("/rooms")
	http.RegisterRoomRoutes(g, m.Handler)
}
