// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/organization/entity"
)

// OrganizationRepository is the contract for persisting Organization aggregates.
type OrganizationRepository interface {
	// Save persists a Organization entity.
	Save(ctx context.Context, e *entity.Organization) error

	// FindByID retrieves a Organization by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Organization, error)

	// FindAll retrieves a paginated list of Organization entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Organization, error)

	// Delete removes a Organization by its primary key.
	Delete(ctx context.Context, id string) error
}
