// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  createZoneSchema,
  type CreateZoneFormData,
} from "../schema";

interface ZoneFormProps {
  onSubmit: (data: CreateZoneFormData) => void;
  defaultValues?: Partial<CreateZoneFormData>;
  isSubmitting?: boolean;
}

export function ZoneForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: ZoneFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateZoneFormData>({
    resolver: zodResolver(createZoneSchema),
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="organization_id">OrganizationId</Label>
        <Input
          id="organization_id"
          {...register("organization_id")}
        />
        {errors.organization_id && (
          <p className="text-sm text-red-500">{errors.organization_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="building_id">BuildingId</Label>
        <Input
          id="building_id"
          {...register("building_id")}
        />
        {errors.building_id && (
          <p className="text-sm text-red-500">{errors.building_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="floor">Floor</Label>
        <Input
          id="floor"
          {...register("floor")}
        />
        {errors.floor && (
          <p className="text-sm text-red-500">{errors.floor.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="name">Name</Label>
        <Input
          id="name"
          {...register("name")}
        />
        {errors.name && (
          <p className="text-sm text-red-500">{errors.name.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting}>
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
