// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useQuery,
  useMutation,
  useQueryClient,
} from "@tanstack/react-query";
import {
  fetchPayments,
  fetchPaymentById,
  createPayment,
  updatePayment,
  deletePayment,
} from "../api";
import type {
  PaymentQueryParams,
  CreatePaymentRequest,
  UpdatePaymentRequest,
} from "../types";

const QUERY_KEY = "payments";
export function usePayments(params?: PaymentQueryParams) {
  return useQuery({
    queryKey: [QUERY_KEY, params],
    queryFn: () => fetchPayments(params),
  });
}
export function usePayment(id: string | undefined) {
  return useQuery({
    queryKey: [QUERY_KEY, id],
    queryFn: () => fetchPaymentById(id!),
    enabled: !!id,
  });
}
export function useCreatePayment() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: CreatePaymentRequest) => createPayment(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useUpdatePayment() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdatePaymentRequest }) =>
      updatePayment(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useDeletePayment() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deletePayment(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
