// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/tenantcontact/entity"
)

// TenantContactRepository is the contract for persisting TenantContact aggregates.
type TenantContactRepository interface {
	// Save persists a TenantContact entity.
	Save(ctx context.Context, e *entity.TenantContact) error

	// FindByID retrieves a TenantContact by its primary key.
	FindByID(ctx context.Context, id string) (*entity.TenantContact, error)

	// FindAll retrieves a paginated list of TenantContact entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.TenantContact, error)

	// Delete removes a TenantContact by its primary key.
	Delete(ctx context.Context, id string) error
}
