// Code generated by epmp-sdk. DO NOT EDIT.

export type PropertyType = "boarding_house" | "apartment" | "villa" | "warehouse";

export interface Property {
  organization_id?: string;
  id: string;
  name: string;
  description?: string;
  address?: string;
  property_type: PropertyType;
  is_active: boolean;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface PropertyListResponse {
  data: Property[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreatePropertyRequest {
  organization_id?: string;
  name: string;
  description?: string;
  address?: string;
  property_type: PropertyType;
  is_active: boolean;
}

export interface UpdatePropertyRequest {
  organization_id?: string;
  name: string;
  description?: string;
  address?: string;
  property_type: PropertyType;
  is_active: boolean;
}

export interface PropertyQueryParams {
  page?: number;
  per_page?: number;
  sort?: string;
  order?: "asc" | "desc";
  search?: string;
  organization_id?: string;
  name?: string;
}
