// Code generated by epmp-sdk. DO NOT EDIT.

package asset

import (
	"github.com/epmp/backend/internal/modules/asset/delivery/http"
	"github.com/epmp/backend/internal/modules/asset/repository"
	"github.com/epmp/backend/internal/modules/asset/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all Asset dependencies.
type Module struct {
	Handler *http.AssetHandler
}

// NewModule creates and wires all Asset dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.AssetRepository = repository.NewAssetRepositoryImpl(db)
	svc := service.NewAssetService(repo)
	handler := http.NewAssetHandler(svc)

	log.Info().Str("module", "asset").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all Asset routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/assets")
	http.RegisterAssetRoutes(g, m.Handler)
}
