// Code generated by epmp-sdk. DO NOT EDIT.

package service

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/room/dto"
	"github.com/epmp/backend/internal/modules/room/entity"
	"github.com/epmp/backend/internal/modules/room/repository"
)

// RoomService implements the application layer for Room.
type RoomService struct {
	repo repository.RoomRepository
}

// NewRoomService creates a new RoomService.
func NewRoomService(repo repository.RoomRepository) *RoomService {
	return &RoomService{repo: repo}
}

func (s *RoomService) Create(ctx context.Context, req *dto.CreateRoomRequest) (*dto.RoomResponse, error) {
	e := entity.NewRoom()
	e.OrganizationId = req.OrganizationId
	e.Name = req.Name
	e.Floor = req.Floor
	e.Capacity = req.Capacity
	e.Price = req.Price
	e.IsAvailable = req.IsAvailable
	e.PropertyId = req.PropertyId

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("room service: create: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *RoomService) GetByID(ctx context.Context, id string) (*dto.RoomResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("room service: get by id: %w", err)
	}
	return s.toResponse(e), nil
}

func (s *RoomService) List(ctx context.Context, page, perPage int) (*dto.RoomListResponse, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 {
		perPage = 20
	}
	offset := (page - 1) * perPage

	items, err := s.repo.FindAll(ctx, perPage, offset)
	if err != nil {
		return nil, fmt.Errorf("room service: list: %w", err)
	}

	data := make([]dto.RoomResponse, 0, len(items))
	for _, e := range items {
		data = append(data, *s.toResponse(e))
	}

	return &dto.RoomListResponse{
		Data:    data,
		Page:    page,
		PerPage: perPage,
	}, nil
}

func (s *RoomService) Update(ctx context.Context, id string, req *dto.UpdateRoomRequest) (*dto.RoomResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("room service: update: find: %w", err)
	}
	e.OrganizationId = req.OrganizationId
	e.Name = req.Name
	e.Floor = req.Floor
	e.Capacity = req.Capacity
	e.Price = req.Price
	e.IsAvailable = req.IsAvailable
	e.PropertyId = req.PropertyId

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("room service: update: save: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *RoomService) Delete(ctx context.Context, id string) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("room service: delete: %w", err)
	}
	return nil
}

func (s *RoomService) toResponse(e *entity.Room) *dto.RoomResponse {
	return &dto.RoomResponse{
		OrganizationId: e.OrganizationId,
		Id: e.Id,
		Name: e.Name,
		Floor: e.Floor,
		Capacity: e.Capacity,
		Price: e.Price,
		IsAvailable: e.IsAvailable,
		PropertyId: e.PropertyId,
	}
}
