// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Supplier,
  SupplierListResponse,
  CreateSupplierRequest,
  UpdateSupplierRequest,
  SupplierQueryParams,
} from "../types";

const BASE_PATH = "/api/vendors";
export async function fetchSuppliers(params?: SupplierQueryParams): Promise<SupplierListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<SupplierListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchSupplierById(id: string): Promise<Supplier> {
  return api.get<Supplier>(`${BASE_PATH}/${id}`);
}
export async function createSupplier(data: CreateSupplierRequest): Promise<Supplier> {
  return api.post<Supplier>(BASE_PATH, data);
}
export async function updateSupplier(id: string, data: UpdateSupplierRequest): Promise<Supplier> {
  return api.put<Supplier>(`${BASE_PATH}/${id}`, data);
}
export async function deleteSupplier(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
