// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Supplier,
  SupplierListResponse,
  CreateSupplierRequest,
  UpdateSupplierRequest,
  SupplierQueryParams,
} from "../types";

const BASE_PATH = "/vendors";
export async function fetchSuppliers(params?: SupplierQueryParams): Promise<SupplierListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: SupplierListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchSupplierById(id: string): Promise<Supplier> {
  const res = await api.get<{ success: boolean; data: Supplier }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createSupplier(data: CreateSupplierRequest): Promise<Supplier> {
  const res = await api.post<{ success: boolean; data: Supplier }>(BASE_PATH, data);
  return res.data;
}
export async function updateSupplier(id: string, data: UpdateSupplierRequest): Promise<Supplier> {
  const res = await api.put<{ success: boolean; data: Supplier }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteSupplier(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
