// Code generated by epmp-sdk. DO NOT EDIT.

export interface Charge {
  organization_id: string;
  id: string;
  contract_id: string;
  invoice_id?: string;
  charge_type: string;
  amount: number;
  status: string;
  charge_date: string;
  notes?: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface ChargeListResponse {
  data: Charge[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreateChargeRequest {
  contract_id: string;
  invoice_id?: string;
  charge_type: string;
  amount: number;
  status: string;
  charge_date: string;
  notes?: string;
}

export interface UpdateChargeRequest {
  contract_id: string;
  invoice_id?: string;
  charge_type: string;
  amount: number;
  status: string;
  charge_date: string;
  notes?: string;
}

export interface ChargeQueryParams {
  page?: number;
  per_page?: number;
  search?: string;
  contract_id?: string;
  invoice_id?: string;
}
