// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const facilitySchema = z.object({
  organization_id: z.string(),
  id: z.string(),
  property_id: z.string(),
  name: z.string().max(100),
  description: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createFacilitySchema = facilitySchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export const updateFacilitySchema = createFacilitySchema.partial();

export type FacilityFormData = z.infer<typeof facilitySchema>;
export type CreateFacilityFormData = z.infer<typeof createFacilitySchema>;
export type UpdateFacilityFormData = z.infer<typeof updateFacilitySchema>;
