// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { usePenalty, useDeletePenalty } from "../hooks";

export function PenaltyDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = usePenalty(id);
  const deleteMutation = useDeletePenalty();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this penalty?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/penalty"),
    });
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Penalty Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/penalty")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/penalty/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">OrganizationId</dt>
          <dd className="text-sm">{String(data.organization_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Id</dt>
          <dd className="text-sm">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">InvoiceId</dt>
          <dd className="text-sm">{String(data.invoice_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Amount</dt>
          <dd className="text-sm">{String(data.amount ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Status</dt>
          <dd className="text-sm">{String(data.status ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">PenaltyDate</dt>
          <dd className="text-sm">{String(data.penalty_date ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Description</dt>
          <dd className="text-sm">{String(data.description ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
