// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreatePenalty } from "../hooks";
import { PenaltyForm } from "../components/PenaltyForm";
import type { CreatePenaltyFormData } from "../schema";

export function PenaltyCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreatePenalty();

  const handleSubmit = (data: CreatePenaltyFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/penalty"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New Penalty</h1>
      <PenaltyForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
