// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate, useParams } from "react-router-dom";
import { useCharge, useUpdateCharge } from "../hooks";
import { ChargeForm } from "../components/ChargeForm";
import type { CreateChargeFormData } from "../schema";

export function ChargeEditPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useCharge(id);
  const updateMutation = useUpdateCharge();

  const handleSubmit = (formData: CreateChargeFormData) => {
    updateMutation.mutate(
      { id: id!, data: formData },
      { onSuccess: () => navigate(`/charge/${id}`) }
    );
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">Edit Charge</h1>
      <ChargeForm
        onSubmit={handleSubmit}
        defaultValues={data}
        isSubmitting={updateMutation.isPending}
      />
    </div>
  );
}
