// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/payment/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// PaymentRepositoryImpl implements PaymentRepository using PostgreSQL.
type PaymentRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewPaymentRepositoryImpl creates a new PaymentRepositoryImpl.
func NewPaymentRepositoryImpl(db *pgxpool.Pool) *PaymentRepositoryImpl {
	return &PaymentRepositoryImpl{db: db}
}

// Ensure PaymentRepositoryImpl implements domain repository interface.
var _ PaymentRepository = (*PaymentRepositoryImpl)(nil)

func (r *PaymentRepositoryImpl) Save(ctx context.Context, e *entity.Payment) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO payments (organization_id, invoice_id, tenant_id, amount, payment_date, payment_method, status, reference_number)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
			RETURNING id`,
			e.OrganizationId, e.InvoiceId, e.TenantId, e.Amount, e.PaymentDate, e.PaymentMethod, e.Status, e.ReferenceNumber,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE payments
		SET    organization_id=$1, invoice_id=$2, tenant_id=$3, amount=$4, payment_date=$5, payment_method=$6, status=$7, reference_number=$8
		WHERE  id=$9 AND deleted_at IS NULL`,
		e.OrganizationId, e.InvoiceId, e.TenantId, e.Amount, e.PaymentDate, e.PaymentMethod, e.Status, e.ReferenceNumber, e.Id,
	)
	return err
}

func (r *PaymentRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Payment, error) {
	e := &entity.Payment{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, invoice_id, tenant_id, amount, payment_date, payment_method, status, reference_number, deleted_at
		FROM   payments
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.InvoiceId, &e.TenantId, &e.Amount, &e.PaymentDate, &e.PaymentMethod, &e.Status, &e.ReferenceNumber, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("payment repository: find by id: %w", err)
	}
	return e, nil
}

func (r *PaymentRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Payment, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, invoice_id, tenant_id, amount, payment_date, payment_method, status, reference_number, deleted_at
		FROM   payments
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("payment repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Payment
	for rows.Next() {
		e := &entity.Payment{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.InvoiceId, &e.TenantId, &e.Amount, &e.PaymentDate, &e.PaymentMethod, &e.Status, &e.ReferenceNumber, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *PaymentRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE payments SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
