// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Occupancy,
  OccupancyListResponse,
  CreateOccupancyRequest,
  UpdateOccupancyRequest,
  OccupancyQueryParams,
} from "../types";

const BASE_PATH = "/api/occupancies";
export async function fetchOccupancys(params?: OccupancyQueryParams): Promise<OccupancyListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<OccupancyListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchOccupancyById(id: string): Promise<Occupancy> {
  return api.get<Occupancy>(`${BASE_PATH}/${id}`);
}
export async function createOccupancy(data: CreateOccupancyRequest): Promise<Occupancy> {
  return api.post<Occupancy>(BASE_PATH, data);
}
export async function updateOccupancy(id: string, data: UpdateOccupancyRequest): Promise<Occupancy> {
  return api.put<Occupancy>(`${BASE_PATH}/${id}`, data);
}
export async function deleteOccupancy(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
