// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateTenantDocument } from "../hooks";
import { TenantDocumentForm } from "../components/TenantDocumentForm";
import type { CreateTenantDocumentFormData } from "../schema";

export function TenantDocumentCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateTenantDocument();

  const handleSubmit = (data: CreateTenantDocumentFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/tenantdocument"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New TenantDocument</h1>
      <TenantDocumentForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
