// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useTenantDocument, useDeleteTenantDocument } from "../hooks";

export function TenantDocumentDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useTenantDocument(id);
  const deleteMutation = useDeleteTenantDocument();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this tenantDocument?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/tenantdocument"),
    });
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">TenantDocument Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/tenantdocument")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/tenantdocument/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">OrganizationId</dt>
          <dd className="text-sm">{String(data.organization_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Id</dt>
          <dd className="text-sm">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">TenantId</dt>
          <dd className="text-sm">{String(data.tenant_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">DocumentType</dt>
          <dd className="text-sm">{String(data.document_type ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">FileUrl</dt>
          <dd className="text-sm">{String(data.file_url ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
