// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useProperty, useDeleteProperty } from "../hooks";

export function PropertyDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useProperty(id);
  const deleteMutation = useDeleteProperty();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this property?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/property"),
    });
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Property Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/property")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/property/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Id</dt>
          <dd className="text-sm">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Name</dt>
          <dd className="text-sm">{String(data.name ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Description</dt>
          <dd className="text-sm">{String(data.description ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Address</dt>
          <dd className="text-sm">{String(data.address ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">PropertyType</dt>
          <dd className="text-sm">{String(data.property_type ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">IsActive</dt>
          <dd className="text-sm">{String(data.is_active ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
