// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useQuery,
  useMutation,
  useQueryClient,
} from "@tanstack/react-query";
import {
  fetchAdjustments,
  fetchAdjustmentById,
  createAdjustment,
  updateAdjustment,
  deleteAdjustment,
} from "../api";
import type {
  AdjustmentQueryParams,
  CreateAdjustmentRequest,
  UpdateAdjustmentRequest,
} from "../types";

const QUERY_KEY = "adjustments";
export function useAdjustments(params?: AdjustmentQueryParams) {
  return useQuery({
    queryKey: [QUERY_KEY, params],
    queryFn: () => fetchAdjustments(params),
  });
}
export function useAdjustment(id: string | undefined) {
  return useQuery({
    queryKey: [QUERY_KEY, id],
    queryFn: () => fetchAdjustmentById(id!),
    enabled: !!id,
  });
}
export function useCreateAdjustment() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateAdjustmentRequest) => createAdjustment(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useUpdateAdjustment() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateAdjustmentRequest }) =>
      updateAdjustment(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useDeleteAdjustment() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteAdjustment(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
