// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useQuery,
  useMutation,
  useQueryClient,
} from "@tanstack/react-query";
import {
  fetchAssetInspections,
  fetchAssetInspectionById,
  createAssetInspection,
  updateAssetInspection,
  deleteAssetInspection,
} from "../api";
import type {
  AssetInspectionQueryParams,
  CreateAssetInspectionRequest,
  UpdateAssetInspectionRequest,
} from "../types";

const QUERY_KEY = "assetInspections";
export function useAssetInspections(params?: AssetInspectionQueryParams) {
  return useQuery({
    queryKey: [QUERY_KEY, params],
    queryFn: () => fetchAssetInspections(params),
  });
}
export function useAssetInspection(id: string | undefined) {
  return useQuery({
    queryKey: [QUERY_KEY, id],
    queryFn: () => fetchAssetInspectionById(id!),
    enabled: !!id,
  });
}
export function useCreateAssetInspection() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateAssetInspectionRequest) => createAssetInspection(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useUpdateAssetInspection() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateAssetInspectionRequest }) =>
      updateAssetInspection(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useDeleteAssetInspection() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteAssetInspection(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
