// Code generated by epmp-sdk. DO NOT EDIT.

package service

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/technician/dto"
	"github.com/epmp/backend/internal/modules/technician/entity"
	"github.com/epmp/backend/internal/modules/technician/repository"
)

// TechnicianService implements the application layer for Technician.
type TechnicianService struct {
	repo repository.TechnicianRepository
}

// NewTechnicianService creates a new TechnicianService.
func NewTechnicianService(repo repository.TechnicianRepository) *TechnicianService {
	return &TechnicianService{repo: repo}
}

func (s *TechnicianService) Create(ctx context.Context, req *dto.CreateTechnicianRequest) (*dto.TechnicianResponse, error) {
	e := entity.NewTechnician()
	e.OrganizationId = req.OrganizationId
	e.Name = req.Name
	e.Phone = req.Phone
	e.Specialty = req.Specialty

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("technician service: create: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *TechnicianService) GetByID(ctx context.Context, id string) (*dto.TechnicianResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("technician service: get by id: %w", err)
	}
	return s.toResponse(e), nil
}

func (s *TechnicianService) List(ctx context.Context, page, perPage int) (*dto.TechnicianListResponse, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 {
		perPage = 20
	}
	offset := (page - 1) * perPage

	items, err := s.repo.FindAll(ctx, perPage, offset)
	if err != nil {
		return nil, fmt.Errorf("technician service: list: %w", err)
	}

	data := make([]dto.TechnicianResponse, 0, len(items))
	for _, e := range items {
		data = append(data, *s.toResponse(e))
	}

	return &dto.TechnicianListResponse{
		Data:    data,
		Page:    page,
		PerPage: perPage,
	}, nil
}

func (s *TechnicianService) Update(ctx context.Context, id string, req *dto.UpdateTechnicianRequest) (*dto.TechnicianResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("technician service: update: find: %w", err)
	}
	e.OrganizationId = req.OrganizationId
	e.Name = req.Name
	e.Phone = req.Phone
	e.Specialty = req.Specialty

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("technician service: update: save: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *TechnicianService) Delete(ctx context.Context, id string) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("technician service: delete: %w", err)
	}
	return nil
}

func (s *TechnicianService) toResponse(e *entity.Technician) *dto.TechnicianResponse {
	return &dto.TechnicianResponse{
		OrganizationId: e.OrganizationId,
		Id: e.Id,
		Name: e.Name,
		Phone: e.Phone,
		Specialty: e.Specialty,
	}
}
