// Code generated by epmp-sdk. DO NOT EDIT.

export interface AssetInspection {
  organization_id: string;
  id: string;
  asset_id: string;
  inspection_date: string;
  condition: string;
  notes?: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface AssetInspectionListResponse {
  data: AssetInspection[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreateAssetInspectionRequest {
  asset_id: string;
  inspection_date: string;
  condition: string;
  notes?: string;
}

export interface UpdateAssetInspectionRequest {
  asset_id: string;
  inspection_date: string;
  condition: string;
  notes?: string;
}

export interface AssetInspectionQueryParams {
  page?: number;
  per_page?: number;
  search?: string;
  asset_id?: string;
}
