// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/facility/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// FacilityRepositoryImpl implements FacilityRepository using PostgreSQL.
type FacilityRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewFacilityRepositoryImpl creates a new FacilityRepositoryImpl.
func NewFacilityRepositoryImpl(db *pgxpool.Pool) *FacilityRepositoryImpl {
	return &FacilityRepositoryImpl{db: db}
}

// Ensure FacilityRepositoryImpl implements domain repository interface.
var _ FacilityRepository = (*FacilityRepositoryImpl)(nil)

func (r *FacilityRepositoryImpl) Save(ctx context.Context, e *entity.Facility) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO facilities (organization_id, property_id, name, description)
			VALUES ($1, $2, $3, $4)
			RETURNING id`,
			e.OrganizationId, e.PropertyId, e.Name, e.Description,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE facilities
		SET    organization_id=$1, property_id=$2, name=$3, description=$4
		WHERE  id=$5 AND deleted_at IS NULL`,
		e.OrganizationId, e.PropertyId, e.Name, e.Description, e.Id,
	)
	return err
}

func (r *FacilityRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Facility, error) {
	e := &entity.Facility{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, property_id, name, description, deleted_at
		FROM   facilities
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.PropertyId, &e.Name, &e.Description, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("facility repository: find by id: %w", err)
	}
	return e, nil
}

func (r *FacilityRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Facility, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, property_id, name, description, deleted_at
		FROM   facilities
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("facility repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Facility
	for rows.Next() {
		e := &entity.Facility{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.PropertyId, &e.Name, &e.Description, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *FacilityRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE facilities SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
