// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/facility/entity"
)

// FacilityRepository is the contract for persisting Facility aggregates.
type FacilityRepository interface {
	// Save persists a Facility entity.
	Save(ctx context.Context, e *entity.Facility) error

	// FindByID retrieves a Facility by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Facility, error)

	// FindAll retrieves a paginated list of Facility entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Facility, error)

	// Delete removes a Facility by its primary key.
	Delete(ctx context.Context, id string) error
}
