// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const contractSchema = z.object({
  organization_id: z.string(),
  id: z.string(),
  reservation_id: z.string().optional(),
  tenant_id: z.string(),
  property_id: z.string(),
  room_id: z.string(),
  status: z.enum(["Draft", "Pending", "Active", "Expired", "Renewed", "Completed", "Terminated"]),
  start_date: z.string(),
  end_date: z.string(),
  monthly_rent: z.number(),
  deposit_amount: z.number(),
  terms: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createContractSchema = contractSchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export const updateContractSchema = createContractSchema.partial();

export type ContractFormData = z.infer<typeof contractSchema>;
export type CreateContractFormData = z.infer<typeof createContractSchema>;
export type UpdateContractFormData = z.infer<typeof updateContractSchema>;
