// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const contractSchema = z.object({
  organization_id: z.string().optional(),
  id: z.string(),
  reservation_id: z.string().optional(),
  tenant_id: z.string().min(1, "Tenant is required"),
  property_id: z.string().min(1, "Property is required"),
  room_id: z.string().min(1, "Room is required"),
  status: z.enum(["Draft", "Pending", "Active", "Expired", "Renewed", "Completed", "Terminated"]),
  start_date: z.string().min(1, "Start date is required"),
  end_date: z.string().min(1, "End date is required"),
  monthly_rent: z.coerce.number().min(0, "Monthly rent must be >= 0"),
  deposit_amount: z.coerce.number().min(0, "Deposit amount must be >= 0"),
  terms: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createContractSchema = contractSchema.omit({
  id: true,
  organization_id: true,
  created_at: true,
  updated_at: true,
});

export const updateContractSchema = createContractSchema.partial();

export type ContractFormData = z.infer<typeof contractSchema>;
export type CreateContractFormData = z.infer<typeof createContractSchema>;
export type UpdateContractFormData = z.infer<typeof updateContractSchema>;
