// Code generated by epmp-sdk. DO NOT EDIT.

package http

import (
	"github.com/labstack/echo/v4"
)

// RegisterTenantContactRoutes registers all TenantContact routes on the given Echo group.
func RegisterTenantContactRoutes(g *echo.Group, h *TenantContactHandler) {
	g.POST("", h.Create)
	g.GET("/:id", h.GetByID)
	g.GET("", h.List)
	g.PUT("/:id", h.Update)
	g.DELETE("/:id", h.Delete)
}
