// Code generated by epmp-sdk. DO NOT EDIT.

package entity

import "time"

// Bed is the domain entity for bed.
type Bed struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	RoomId string `json:"room_id"`
	Name string `json:"name"`
	Status string `json:"status"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewBed creates a new Bed instance.
func NewBed() *Bed {
	return &Bed{}
}
