// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/asset/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// AssetRepositoryImpl implements AssetRepository using PostgreSQL.
type AssetRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewAssetRepositoryImpl creates a new AssetRepositoryImpl.
func NewAssetRepositoryImpl(db *pgxpool.Pool) *AssetRepositoryImpl {
	return &AssetRepositoryImpl{db: db}
}

// Ensure AssetRepositoryImpl implements domain repository interface.
var _ AssetRepository = (*AssetRepositoryImpl)(nil)

func (r *AssetRepositoryImpl) Save(ctx context.Context, e *entity.Asset) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO assets (organization_id, property_id, name, category, status, purchase_price)
			VALUES ($1, $2, $3, $4, $5, $6)
			RETURNING id`,
			e.OrganizationId, e.PropertyId, e.Name, e.Category, e.Status, e.PurchasePrice,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE assets
		SET    organization_id=$1, property_id=$2, name=$3, category=$4, status=$5, purchase_price=$6
		WHERE  id=$7 AND deleted_at IS NULL`,
		e.OrganizationId, e.PropertyId, e.Name, e.Category, e.Status, e.PurchasePrice, e.Id,
	)
	return err
}

func (r *AssetRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Asset, error) {
	e := &entity.Asset{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, property_id, name, category, status, purchase_price, deleted_at
		FROM   assets
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.PropertyId, &e.Name, &e.Category, &e.Status, &e.PurchasePrice, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("asset repository: find by id: %w", err)
	}
	return e, nil
}

func (r *AssetRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Asset, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, property_id, name, category, status, purchase_price, deleted_at
		FROM   assets
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("asset repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Asset
	for rows.Next() {
		e := &entity.Asset{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.PropertyId, &e.Name, &e.Category, &e.Status, &e.PurchasePrice, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *AssetRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE assets SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
