// Code generated by epmp-sdk. DO NOT EDIT.

package dto

import "time"

// CreateFacilityRequest is the DTO for creating a Facility.
type CreateFacilityRequest struct {
	OrganizationId string `json:"organization_id"`
	PropertyId string `json:"property_id"`
	Name string `json:"name"`
	Description string `json:"description"`
}

// UpdateFacilityRequest is the DTO for updating a Facility.
type UpdateFacilityRequest struct {
	OrganizationId string `json:"organization_id"`
	PropertyId string `json:"property_id"`
	Name string `json:"name"`
	Description string `json:"description"`
}

// FacilityResponse is the DTO for returning a Facility.
type FacilityResponse struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	PropertyId string `json:"property_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// FacilityListResponse is the DTO for a paginated list of Facility.
type FacilityListResponse struct {
	Data       []FacilityResponse `json:"data"`
	Total      int64               `json:"total"`
	Page       int                 `json:"page"`
	PerPage    int                 `json:"per_page"`
	TotalPages int                 `json:"total_pages"`
}
