// Code generated by epmp-sdk. DO NOT EDIT.

package reservation

import (
	"github.com/epmp/backend/internal/modules/reservation/delivery/http"
	"github.com/epmp/backend/internal/modules/reservation/repository"
	"github.com/epmp/backend/internal/modules/reservation/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all Reservation dependencies.
type Module struct {
	Handler *http.ReservationHandler
}

// NewModule creates and wires all Reservation dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.ReservationRepository = repository.NewReservationRepositoryImpl(db)
	svc := service.NewReservationService(repo)
	handler := http.NewReservationHandler(svc)

	log.Info().Str("module", "reservation").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all Reservation routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/reservations")
	http.RegisterReservationRoutes(g, m.Handler)
}
