// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useReservation, useDeleteReservation } from "../hooks";

export function ReservationDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useReservation(id);
  const deleteMutation = useDeleteReservation();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this reservation?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/dashboard/reservations"),
    });
  };

  if (isLoading) return <div className="text-center py-12 text-slate-400">Loading...</div>;
  if (!data) return <div className="text-center py-12 text-slate-400">Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Reservation Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/dashboard/reservations")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/dashboard/reservations/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2 bg-white rounded-xl border border-slate-200 shadow-sm p-6">
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">OrganizationId</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.organization_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Id</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">TenantId</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.tenant_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">PropertyId</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.property_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">RoomId</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.room_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Status</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.status ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">CheckInDate</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.check_in_date ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">CheckOutDate</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.check_out_date ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">BookingFee</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.booking_fee ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Notes</dt>
          <dd className="text-sm text-slate-800 mt-1">{String(data.notes ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
