// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useInvoice, useDeleteInvoice } from "../hooks";

export function InvoiceDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useInvoice(id);
  const deleteMutation = useDeleteInvoice();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this invoice?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/billing"),
    });
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Invoice Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/billing")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/billing/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">OrganizationId</dt>
          <dd className="text-sm">{String(data.organization_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Id</dt>
          <dd className="text-sm">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">ContractId</dt>
          <dd className="text-sm">{String(data.contract_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">TenantId</dt>
          <dd className="text-sm">{String(data.tenant_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Amount</dt>
          <dd className="text-sm">{String(data.amount ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Status</dt>
          <dd className="text-sm">{String(data.status ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">DueDate</dt>
          <dd className="text-sm">{String(data.due_date ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">PaidDate</dt>
          <dd className="text-sm">{String(data.paid_date ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">PaymentMethod</dt>
          <dd className="text-sm">{String(data.payment_method ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Notes</dt>
          <dd className="text-sm">{String(data.notes ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
