// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateInvoice } from "../hooks";
import { InvoiceForm } from "../components/InvoiceForm";
import type { CreateInvoiceFormData } from "../schema";

export function InvoiceCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateInvoice();

  const handleSubmit = (data: CreateInvoiceFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/billing"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New Invoice</h1>
      <InvoiceForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
