// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  createColumnHelper,
} from "@tanstack/react-table";
import type { Contract } from "../types";
import { useReservations } from "../../reservation/hooks";
import { useTenants } from "../../tenant/hooks";
import { usePropertys } from "../../property/hooks";
import { useRooms } from "../../room/hooks";

import { AlertBadge } from "@/components/ui/AlertBadge";
import { formatCurrency } from "@/utils/currency";

const columnHelper = createColumnHelper<Contract>();


interface ContractTableProps {
  data: Contract[];
  onRowClick?: (row: Contract) => void;
}

export function ContractTable({ data, onRowClick }: ContractTableProps) {
  const { data: reservationsData } = useReservations({ per_page: 100 });
  const { data: tenantsData } = useTenants({ per_page: 100 });
  const { data: propertiesData } = usePropertys({ per_page: 100 });
  const { data: roomsData } = useRooms({ per_page: 100 });
  const reservationsMap = new Map(
    (Array.isArray(reservationsData?.data) ? reservationsData.data : Array.isArray(reservationsData) ? reservationsData : [])
      .map((item: any) => [item.id, `#` + item.id.slice(0, 8)])
  );
  const tenantsMap = new Map(
    (Array.isArray(tenantsData?.data) ? tenantsData.data : Array.isArray(tenantsData) ? tenantsData : [])
      .map((item: any) => [item.id, item.full_name])
  );
  const propertiesMap = new Map(
    (Array.isArray(propertiesData?.data) ? propertiesData.data : Array.isArray(propertiesData) ? propertiesData : [])
      .map((item: any) => [item.id, item.name])
  );
  const roomsMap = new Map(
    (Array.isArray(roomsData?.data) ? roomsData.data : Array.isArray(roomsData) ? roomsData : [])
      .map((item: any) => [item.id, item.name])
  );

  const columns = [
    columnHelper.accessor("reservation_id", {
      header: "Reservation",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        return reservationsMap.get(id) || <span className="text-slate-400 font-mono text-xs">#{id.slice(0, 8)}</span>;
      },
    }),
    columnHelper.accessor("tenant_id", {
      header: "Tenant",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        return tenantsMap.get(id) || <span className="text-slate-400 font-mono text-xs">#{id.slice(0, 8)}</span>;
      },
    }),
    columnHelper.accessor("property_id", {
      header: "Property",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        return propertiesMap.get(id) || <span className="text-slate-400 font-mono text-xs">#{id.slice(0, 8)}</span>;
      },
    }),
    columnHelper.accessor("room_id", {
      header: "Room",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        return roomsMap.get(id) || <span className="text-slate-400 font-mono text-xs">#{id.slice(0, 8)}</span>;
      },
    }),
    columnHelper.accessor("status", {
      header: "Status & Tanda Khusus",
      cell: (info) => {
        const status = info.getValue() as string;
        const row = info.row.original;
        if (status === "Terminated") {
          return <span className="text-xs px-2 py-0.5 rounded-full bg-slate-100 text-slate-500 font-medium">Terminated</span>;
        }
        if (status === "Expired") {
          return <AlertBadge variant="expired" label="Habis Kontrak" />;
        }
        if (row.end_date) {
          const now = new Date();
          const end = new Date(row.end_date);
          const diffDays = Math.ceil((end.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
          if (diffDays < 0) {
            return <AlertBadge variant="expired" label="Habis Kontrak" />;
          } else if (diffDays <= 30) {
            return <AlertBadge variant="expiring_soon" label={`Akan Habis (H-${diffDays})`} />;
          }
        }
        return <AlertBadge variant="active" label={status || "Aktif"} />;
      },
    }),
    columnHelper.accessor("start_date", {
      header: "Start Date",
      cell: (info) => {
        const val = info.getValue() as string;
        if (!val) return <span className="text-slate-400">—</span>;
        return new Date(val).toLocaleDateString("id-ID", {
          day: "numeric",
          month: "short",
          year: "numeric",
        });
      },
    }),
    columnHelper.accessor("end_date", {
      header: "End Date",
      cell: (info) => {
        const val = info.getValue() as string;
        if (!val) return <span className="text-slate-400">—</span>;
        return new Date(val).toLocaleDateString("id-ID", {
          day: "numeric",
          month: "short",
          year: "numeric",
        });
      },
    }),
    columnHelper.accessor("monthly_rent", {
      header: "Monthly Rent",
      cell: (info) => {
        const val = info.getValue();
        const row = info.row.original;
        return formatCurrency(val, (row as any).currency || "IDR");
      },
    }),
    columnHelper.accessor("deposit_amount", {
      header: "Deposit Amount",
      cell: (info) => {
        const val = info.getValue();
        const row = info.row.original;
        return formatCurrency(val, (row as any).currency || "IDR");
      },
    }),
    columnHelper.accessor("terms", {
      header: "Terms",
      cell: (info) => info.getValue(),
    }),
  ];

  const table = useReactTable({
    data: data || [],
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  return (
    <div className="rounded-xl border border-slate-200 bg-white overflow-hidden shadow-sm">
      <table className="w-full text-sm text-left">
        <thead className="border-b border-slate-200 bg-slate-50/75 text-slate-600 font-semibold">
          {table.getHeaderGroups().map((headerGroup) => (
            <tr key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <th key={header.id} className="px-5 py-3.5">
                  {flexRender(
                    header.column.columnDef.header,
                    header.getContext()
                  )}
                </th>
              ))}
            </tr>
          ))}
        </thead>
        <tbody className="divide-y divide-slate-100">
          {table.getRowModel().rows.map((row) => (
            <tr
              key={row.id}
              className="hover:bg-orange/5 cursor-pointer transition-colors"
              onClick={() => onRowClick?.(row.original)}
            >
              {row.getVisibleCells().map((cell) => (
                <td key={cell.id} className="px-5 py-4">
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </td>
              ))}
            </tr>
          ))}
          {table.getRowModel().rows.length === 0 && (
            <tr>
              <td colSpan={columns.length} className="px-5 py-12 text-center text-slate-400">
                No data found.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}
