// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/reservation/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// ReservationRepositoryImpl implements ReservationRepository using PostgreSQL.
type ReservationRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewReservationRepositoryImpl creates a new ReservationRepositoryImpl.
func NewReservationRepositoryImpl(db *pgxpool.Pool) *ReservationRepositoryImpl {
	return &ReservationRepositoryImpl{db: db}
}

// Ensure ReservationRepositoryImpl implements domain repository interface.
var _ ReservationRepository = (*ReservationRepositoryImpl)(nil)

func (r *ReservationRepositoryImpl) Save(ctx context.Context, e *entity.Reservation) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO reservations (tenant_id, property_id, room_id, status, check_in_date, check_out_date, booking_fee, notes)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
			RETURNING id`,
			e.TenantId, e.PropertyId, e.RoomId, e.Status, e.CheckInDate, e.CheckOutDate, e.BookingFee, e.Notes,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE reservations
		SET    tenant_id=$1, property_id=$2, room_id=$3, status=$4, check_in_date=$5, check_out_date=$6, booking_fee=$7, notes=$8
		WHERE  id=$9 AND deleted_at IS NULL`,
		e.TenantId, e.PropertyId, e.RoomId, e.Status, e.CheckInDate, e.CheckOutDate, e.BookingFee, e.Notes, e.Id,
	)
	return err
}

func (r *ReservationRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Reservation, error) {
	e := &entity.Reservation{}
	err := r.db.QueryRow(ctx, `
		SELECT id, tenant_id, property_id, room_id, status, check_in_date, check_out_date, booking_fee, notes, deleted_at
		FROM   reservations
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.Id, &e.TenantId, &e.PropertyId, &e.RoomId, &e.Status, &e.CheckInDate, &e.CheckOutDate, &e.BookingFee, &e.Notes, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("reservation repository: find by id: %w", err)
	}
	return e, nil
}

func (r *ReservationRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Reservation, error) {
	rows, err := r.db.Query(ctx, `
		SELECT id, tenant_id, property_id, room_id, status, check_in_date, check_out_date, booking_fee, notes, deleted_at
		FROM   reservations
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("reservation repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Reservation
	for rows.Next() {
		e := &entity.Reservation{}
		if err := rows.Scan(&e.Id, &e.TenantId, &e.PropertyId, &e.RoomId, &e.Status, &e.CheckInDate, &e.CheckOutDate, &e.BookingFee, &e.Notes, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *ReservationRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE reservations SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
