// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  createPropertySchema,
  type CreatePropertyFormData,
} from "../schema";

interface PropertyFormProps {
  onSubmit: (data: CreatePropertyFormData) => void;
  defaultValues?: Partial<CreatePropertyFormData>;
  isSubmitting?: boolean;
}

export function PropertyForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: PropertyFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreatePropertyFormData>({
    resolver: zodResolver(createPropertySchema),
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="name">Name</Label>
        <Input
          id="name"
          {...register("name")}
        />
        {errors.name && (
          <p className="text-sm text-red-500">{errors.name.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="description">Description</Label>
        <Input
          id="description"
          {...register("description")}
        />
        {errors.description && (
          <p className="text-sm text-red-500">{errors.description.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="address">Address</Label>
        <Input
          id="address"
          {...register("address")}
        />
        {errors.address && (
          <p className="text-sm text-red-500">{errors.address.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="property_type">PropertyType</Label>
        <Input
          id="property_type"
          {...register("property_type")}
        />
        {errors.property_type && (
          <p className="text-sm text-red-500">{errors.property_type.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="is_active">IsActive</Label>
        <Input
          id="is_active"
          {...register("is_active")}
        />
        {errors.is_active && (
          <p className="text-sm text-red-500">{errors.is_active.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting}>
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
