// Code generated by epmp-sdk. DO NOT EDIT.

package dto

import "time"

// CreateOrganizationRequest is the DTO for creating a Organization.
type CreateOrganizationRequest struct {
	Name string `json:"name"`
	Domain string `json:"domain"`
	IsActive bool `json:"is_active"`
}

// UpdateOrganizationRequest is the DTO for updating a Organization.
type UpdateOrganizationRequest struct {
	Name string `json:"name"`
	Domain string `json:"domain"`
	IsActive bool `json:"is_active"`
}

// OrganizationResponse is the DTO for returning a Organization.
type OrganizationResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Domain string `json:"domain"`
	IsActive bool `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// OrganizationListResponse is the DTO for a paginated list of Organization.
type OrganizationListResponse struct {
	Data       []OrganizationResponse `json:"data"`
	Total      int64               `json:"total"`
	Page       int                 `json:"page"`
	PerPage    int                 `json:"per_page"`
	TotalPages int                 `json:"total_pages"`
}
