// Code generated by epmp-sdk. DO NOT EDIT.

package dto

import "time"

// CreateTechnicianRequest is the DTO for creating a Technician.
type CreateTechnicianRequest struct {
	OrganizationId string `json:"organization_id"`
	Name string `json:"name"`
	Phone string `json:"phone"`
	Specialty string `json:"specialty"`
}

// UpdateTechnicianRequest is the DTO for updating a Technician.
type UpdateTechnicianRequest struct {
	OrganizationId string `json:"organization_id"`
	Name string `json:"name"`
	Phone string `json:"phone"`
	Specialty string `json:"specialty"`
}

// TechnicianResponse is the DTO for returning a Technician.
type TechnicianResponse struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	Name string `json:"name"`
	Phone string `json:"phone"`
	Specialty string `json:"specialty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TechnicianListResponse is the DTO for a paginated list of Technician.
type TechnicianListResponse struct {
	Data       []TechnicianResponse `json:"data"`
	Total      int64               `json:"total"`
	Page       int                 `json:"page"`
	PerPage    int                 `json:"per_page"`
	TotalPages int                 `json:"total_pages"`
}
