// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  createTenantIdentitySchema,
  type CreateTenantIdentityFormData,
} from "../schema";

interface TenantIdentityFormProps {
  onSubmit: (data: CreateTenantIdentityFormData) => void;
  defaultValues?: Partial<CreateTenantIdentityFormData>;
  isSubmitting?: boolean;
}

export function TenantIdentityForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: TenantIdentityFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateTenantIdentityFormData>({
    resolver: zodResolver(createTenantIdentitySchema),
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="organization_id">OrganizationId</Label>
        <Input
          id="organization_id"
          {...register("organization_id")}
        />
        {errors.organization_id && (
          <p className="text-sm text-red-500">{errors.organization_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="tenant_id">TenantId</Label>
        <Input
          id="tenant_id"
          {...register("tenant_id")}
        />
        {errors.tenant_id && (
          <p className="text-sm text-red-500">{errors.tenant_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="identity_type">IdentityType</Label>
        <Input
          id="identity_type"
          {...register("identity_type")}
        />
        {errors.identity_type && (
          <p className="text-sm text-red-500">{errors.identity_type.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="identity_number">IdentityNumber</Label>
        <Input
          id="identity_number"
          {...register("identity_number")}
        />
        {errors.identity_number && (
          <p className="text-sm text-red-500">{errors.identity_number.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="file_url">FileUrl</Label>
        <Input
          id="file_url"
          {...register("file_url")}
        />
        {errors.file_url && (
          <p className="text-sm text-red-500">{errors.file_url.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting}>
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
