// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/workorder/entity"
)

// WorkOrderRepository is the contract for persisting WorkOrder aggregates.
type WorkOrderRepository interface {
	// Save persists a WorkOrder entity.
	Save(ctx context.Context, e *entity.WorkOrder) error

	// FindByID retrieves a WorkOrder by its primary key.
	FindByID(ctx context.Context, id string) (*entity.WorkOrder, error)

	// FindAll retrieves a paginated list of WorkOrder entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.WorkOrder, error)

	// Delete removes a WorkOrder by its primary key.
	Delete(ctx context.Context, id string) error
}
