// Code generated by epmp-sdk. DO NOT EDIT.

package entity

import "time"

// Building is the domain entity for building.
type Building struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	PropertyId string `json:"property_id"`
	Name string `json:"name"`
	TotalFloors int `json:"total_floors"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewBuilding creates a new Building instance.
func NewBuilding() *Building {
	return &Building{}
}
