// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate, useParams } from "react-router-dom";
import { useTenantContact, useUpdateTenantContact } from "../hooks";
import { TenantContactForm } from "../components/TenantContactForm";
import type { CreateTenantContactFormData } from "../schema";

export function TenantContactEditPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useTenantContact(id);
  const updateMutation = useUpdateTenantContact();

  const handleSubmit = (formData: CreateTenantContactFormData) => {
    updateMutation.mutate(
      { id: id!, data: formData },
      { onSuccess: () => navigate(`/tenantcontact/${id}`) }
    );
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">Edit TenantContact</h1>
      <TenantContactForm
        onSubmit={handleSubmit}
        defaultValues={data}
        isSubmitting={updateMutation.isPending}
      />
    </div>
  );
}
