// Code generated by epmp-sdk. DO NOT EDIT.

export interface Adjustment {
  organization_id: string;
  id: string;
  invoice_id: string;
  adjustment_type: string;
  amount: number;
  adjustment_date: string;
  reason: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface AdjustmentListResponse {
  data: Adjustment[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreateAdjustmentRequest {
  organization_id: string;
  invoice_id: string;
  adjustment_type: string;
  amount: number;
  adjustment_date: string;
  reason: string;
}

export interface UpdateAdjustmentRequest {
  organization_id: string;
  invoice_id: string;
  adjustment_type: string;
  amount: number;
  adjustment_date: string;
  reason: string;
}

export interface AdjustmentQueryParams {
  page?: number;
  per_page?: number;
  sort?: string;
  order?: "asc" | "desc";
  search?: string;
  organization_id?: string;
  invoice_id?: string;
}
