// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/technician/entity"
)

// TechnicianRepository is the contract for persisting Technician aggregates.
type TechnicianRepository interface {
	// Save persists a Technician entity.
	Save(ctx context.Context, e *entity.Technician) error

	// FindByID retrieves a Technician by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Technician, error)

	// FindAll retrieves a paginated list of Technician entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Technician, error)

	// Delete removes a Technician by its primary key.
	Delete(ctx context.Context, id string) error
}
