// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/technician/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// TechnicianRepositoryImpl implements TechnicianRepository using PostgreSQL.
type TechnicianRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewTechnicianRepositoryImpl creates a new TechnicianRepositoryImpl.
func NewTechnicianRepositoryImpl(db *pgxpool.Pool) *TechnicianRepositoryImpl {
	return &TechnicianRepositoryImpl{db: db}
}

// Ensure TechnicianRepositoryImpl implements domain repository interface.
var _ TechnicianRepository = (*TechnicianRepositoryImpl)(nil)

func (r *TechnicianRepositoryImpl) Save(ctx context.Context, e *entity.Technician) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO technicians (organization_id, name, phone, specialty)
			VALUES ($1, $2, $3, $4)
			RETURNING id`,
			e.OrganizationId, e.Name, e.Phone, e.Specialty,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE technicians
		SET    organization_id=$1, name=$2, phone=$3, specialty=$4
		WHERE  id=$5 AND deleted_at IS NULL`,
		e.OrganizationId, e.Name, e.Phone, e.Specialty, e.Id,
	)
	return err
}

func (r *TechnicianRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Technician, error) {
	e := &entity.Technician{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, name, phone, specialty, deleted_at
		FROM   technicians
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.Name, &e.Phone, &e.Specialty, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("technician repository: find by id: %w", err)
	}
	return e, nil
}

func (r *TechnicianRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Technician, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, name, phone, specialty, deleted_at
		FROM   technicians
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("technician repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Technician
	for rows.Next() {
		e := &entity.Technician{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.Name, &e.Phone, &e.Specialty, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *TechnicianRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE technicians SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
