// Code generated by epmp-sdk. DO NOT EDIT.

package technician

import (
	"github.com/epmp/backend/internal/modules/technician/delivery/http"
	"github.com/epmp/backend/internal/modules/technician/repository"
	"github.com/epmp/backend/internal/modules/technician/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all Technician dependencies.
type Module struct {
	Handler *http.TechnicianHandler
}

// NewModule creates and wires all Technician dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.TechnicianRepository = repository.NewTechnicianRepositoryImpl(db)
	svc := service.NewTechnicianService(repo)
	handler := http.NewTechnicianHandler(svc)

	log.Info().Str("module", "technician").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all Technician routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/technicians")
	http.RegisterTechnicianRoutes(g, m.Handler)
}
