// Code generated by epmp-sdk. DO NOT EDIT.

package http

import (
	"strconv"

	"github.com/epmp/backend/internal/modules/assetinspection/dto"
	"github.com/epmp/backend/internal/modules/assetinspection/service"
	"github.com/epmp/backend/internal/pkg/response"

	"github.com/labstack/echo/v4"
)

// AssetInspectionHandler handles HTTP requests for AssetInspection resources.
type AssetInspectionHandler struct {
	svc *service.AssetInspectionService
}

// NewAssetInspectionHandler creates a new AssetInspectionHandler.
func NewAssetInspectionHandler(svc *service.AssetInspectionService) *AssetInspectionHandler {
	return &AssetInspectionHandler{svc: svc}
}

func (h *AssetInspectionHandler) Create(c echo.Context) error {
	var req dto.CreateAssetInspectionRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Create(c.Request().Context(), &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.Created(c, result)
}

func (h *AssetInspectionHandler) GetByID(c echo.Context) error {
	id := c.Param("id")

	result, err := h.svc.GetByID(c.Request().Context(), id)
	if err != nil {
		return response.NotFound(c, "AssetInspection not found")
	}

	return response.OK(c, result)
}

func (h *AssetInspectionHandler) List(c echo.Context) error {
	page, _ := strconv.Atoi(c.QueryParam("page"))
	if page == 0 {
		page = 1
	}
	perPage, _ := strconv.Atoi(c.QueryParam("per_page"))
	if perPage == 0 {
		perPage = 20
	}

	result, err := h.svc.List(c.Request().Context(), page, perPage)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *AssetInspectionHandler) Update(c echo.Context) error {
	id := c.Param("id")

	var req dto.UpdateAssetInspectionRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Update(c.Request().Context(), id, &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *AssetInspectionHandler) Delete(c echo.Context) error {
	id := c.Param("id")

	if err := h.svc.Delete(c.Request().Context(), id); err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.NoContent(c)
}
