// Code generated by epmp-sdk. DO NOT EDIT.

export interface Payment {
  organization_id: string;
  id: string;
  invoice_id: string;
  tenant_id: string;
  amount: number;
  payment_date: string;
  payment_method: string;
  status: string;
  reference_number?: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface PaymentListResponse {
  data: Payment[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreatePaymentRequest {
  invoice_id: string;
  tenant_id: string;
  amount: number;
  payment_date: string;
  payment_method: string;
  status: string;
  reference_number?: string;
}

export interface UpdatePaymentRequest {
  invoice_id: string;
  tenant_id: string;
  amount: number;
  payment_date: string;
  payment_method: string;
  status: string;
  reference_number?: string;
}

export interface PaymentQueryParams {
  page?: number;
  per_page?: number;
  search?: string;
  invoice_id?: string;
  tenant_id?: string;
}
