// Code generated by epmp-sdk. DO NOT EDIT.

package assetassignment

import (
	"github.com/epmp/backend/internal/modules/assetassignment/delivery/http"
	"github.com/epmp/backend/internal/modules/assetassignment/repository"
	"github.com/epmp/backend/internal/modules/assetassignment/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all AssetAssignment dependencies.
type Module struct {
	Handler *http.AssetAssignmentHandler
}

// NewModule creates and wires all AssetAssignment dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.AssetAssignmentRepository = repository.NewAssetAssignmentRepositoryImpl(db)
	svc := service.NewAssetAssignmentService(repo)
	handler := http.NewAssetAssignmentHandler(svc)

	log.Info().Str("module", "assetassignment").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all AssetAssignment routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/asset_assignments")
	http.RegisterAssetAssignmentRoutes(g, m.Handler)
}
