// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate, useParams } from "react-router-dom";
import { useZone, useUpdateZone } from "../hooks";
import { ZoneForm } from "../components/ZoneForm";
import type { CreateZoneFormData } from "../schema";

export function ZoneEditPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useZone(id);
  const updateMutation = useUpdateZone();

  const handleSubmit = (formData: CreateZoneFormData) => {
    updateMutation.mutate(
      { id: id!, data: formData },
      { onSuccess: () => navigate(`/zone/${id}`) }
    );
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">Edit Zone</h1>
      <ZoneForm
        onSubmit={handleSubmit}
        defaultValues={data}
        isSubmitting={updateMutation.isPending}
      />
    </div>
  );
}
