// Code generated by epmp-sdk. DO NOT EDIT.

package entity

import "time"

// Charge is the domain entity for charge.
type Charge struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	ContractId string `json:"contract_id"`
	InvoiceId string `json:"invoice_id"`
	ChargeType string `json:"charge_type"`
	Amount float64 `json:"amount"`
	Status string `json:"status"`
	ChargeDate time.Time `json:"charge_date"`
	Notes string `json:"notes"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewCharge creates a new Charge instance.
func NewCharge() *Charge {
	return &Charge{}
}
