// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/charge/entity"
)

// ChargeRepository is the contract for persisting Charge aggregates.
type ChargeRepository interface {
	// Save persists a Charge entity.
	Save(ctx context.Context, e *entity.Charge) error

	// FindByID retrieves a Charge by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Charge, error)

	// FindAll retrieves a paginated list of Charge entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Charge, error)

	// Delete removes a Charge by its primary key.
	Delete(ctx context.Context, id string) error
}
