// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/charge/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// ChargeRepositoryImpl implements ChargeRepository using PostgreSQL.
type ChargeRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewChargeRepositoryImpl creates a new ChargeRepositoryImpl.
func NewChargeRepositoryImpl(db *pgxpool.Pool) *ChargeRepositoryImpl {
	return &ChargeRepositoryImpl{db: db}
}

// Ensure ChargeRepositoryImpl implements domain repository interface.
var _ ChargeRepository = (*ChargeRepositoryImpl)(nil)

func (r *ChargeRepositoryImpl) Save(ctx context.Context, e *entity.Charge) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO charges (organization_id, contract_id, invoice_id, charge_type, amount, status, charge_date, notes)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
			RETURNING id`,
			e.OrganizationId, e.ContractId, e.InvoiceId, e.ChargeType, e.Amount, e.Status, e.ChargeDate, e.Notes,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE charges
		SET    organization_id=$1, contract_id=$2, invoice_id=$3, charge_type=$4, amount=$5, status=$6, charge_date=$7, notes=$8
		WHERE  id=$9 AND deleted_at IS NULL`,
		e.OrganizationId, e.ContractId, e.InvoiceId, e.ChargeType, e.Amount, e.Status, e.ChargeDate, e.Notes, e.Id,
	)
	return err
}

func (r *ChargeRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Charge, error) {
	e := &entity.Charge{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, contract_id, invoice_id, charge_type, amount, status, charge_date, notes, deleted_at
		FROM   charges
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.ContractId, &e.InvoiceId, &e.ChargeType, &e.Amount, &e.Status, &e.ChargeDate, &e.Notes, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("charge repository: find by id: %w", err)
	}
	return e, nil
}

func (r *ChargeRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Charge, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, contract_id, invoice_id, charge_type, amount, status, charge_date, notes, deleted_at
		FROM   charges
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("charge repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Charge
	for rows.Next() {
		e := &entity.Charge{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.ContractId, &e.InvoiceId, &e.ChargeType, &e.Amount, &e.Status, &e.ChargeDate, &e.Notes, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *ChargeRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE charges SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
