// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/penalty/entity"
)

// PenaltyRepository is the contract for persisting Penalty aggregates.
type PenaltyRepository interface {
	// Save persists a Penalty entity.
	Save(ctx context.Context, e *entity.Penalty) error

	// FindByID retrieves a Penalty by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Penalty, error)

	// FindAll retrieves a paginated list of Penalty entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Penalty, error)

	// Delete removes a Penalty by its primary key.
	Delete(ctx context.Context, id string) error
}
