// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useQuery,
  useMutation,
  useQueryClient,
} from "@tanstack/react-query";
import {
  fetchBuildings,
  fetchBuildingById,
  createBuilding,
  updateBuilding,
  deleteBuilding,
} from "../api";
import type {
  BuildingQueryParams,
  CreateBuildingRequest,
  UpdateBuildingRequest,
} from "../types";

const QUERY_KEY = "buildings";
export function useBuildings(params?: BuildingQueryParams) {
  return useQuery({
    queryKey: [QUERY_KEY, params],
    queryFn: () => fetchBuildings(params),
  });
}
export function useBuilding(id: string | undefined) {
  return useQuery({
    queryKey: [QUERY_KEY, id],
    queryFn: () => fetchBuildingById(id!),
    enabled: !!id,
  });
}
export function useCreateBuilding() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateBuildingRequest) => createBuilding(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useUpdateBuilding() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateBuildingRequest }) =>
      updateBuilding(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useDeleteBuilding() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteBuilding(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
