// Code generated by epmp-sdk. DO NOT EDIT.

package http

import (
	"strconv"

	"github.com/epmp/backend/internal/modules/technician/dto"
	"github.com/epmp/backend/internal/modules/technician/service"
	"github.com/epmp/backend/internal/pkg/response"

	"github.com/labstack/echo/v4"
)

// TechnicianHandler handles HTTP requests for Technician resources.
type TechnicianHandler struct {
	svc *service.TechnicianService
}

// NewTechnicianHandler creates a new TechnicianHandler.
func NewTechnicianHandler(svc *service.TechnicianService) *TechnicianHandler {
	return &TechnicianHandler{svc: svc}
}

func (h *TechnicianHandler) Create(c echo.Context) error {
	var req dto.CreateTechnicianRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Create(c.Request().Context(), &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.Created(c, result)
}

func (h *TechnicianHandler) GetByID(c echo.Context) error {
	id := c.Param("id")

	result, err := h.svc.GetByID(c.Request().Context(), id)
	if err != nil {
		return response.NotFound(c, "Technician not found")
	}

	return response.OK(c, result)
}

func (h *TechnicianHandler) List(c echo.Context) error {
	page, _ := strconv.Atoi(c.QueryParam("page"))
	if page == 0 {
		page = 1
	}
	perPage, _ := strconv.Atoi(c.QueryParam("per_page"))
	if perPage == 0 {
		perPage = 20
	}

	result, err := h.svc.List(c.Request().Context(), page, perPage)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *TechnicianHandler) Update(c echo.Context) error {
	id := c.Param("id")

	var req dto.UpdateTechnicianRequest
	if err := c.Bind(&req); err != nil {
		return response.BadRequest(c, "invalid request body")
	}

	result, err := h.svc.Update(c.Request().Context(), id, &req)
	if err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.OK(c, result)
}

func (h *TechnicianHandler) Delete(c echo.Context) error {
	id := c.Param("id")

	if err := h.svc.Delete(c.Request().Context(), id); err != nil {
		return response.InternalError(c, err.Error())
	}

	return response.NoContent(c)
}
