// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/roomtype/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// RoomTypeRepositoryImpl implements RoomTypeRepository using PostgreSQL.
type RoomTypeRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewRoomTypeRepositoryImpl creates a new RoomTypeRepositoryImpl.
func NewRoomTypeRepositoryImpl(db *pgxpool.Pool) *RoomTypeRepositoryImpl {
	return &RoomTypeRepositoryImpl{db: db}
}

// Ensure RoomTypeRepositoryImpl implements domain repository interface.
var _ RoomTypeRepository = (*RoomTypeRepositoryImpl)(nil)

func (r *RoomTypeRepositoryImpl) Save(ctx context.Context, e *entity.RoomType) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO room_types (organization_id, name, description, base_price)
			VALUES ($1, $2, $3, $4)
			RETURNING id`,
			e.OrganizationId, e.Name, e.Description, e.BasePrice,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE room_types
		SET    organization_id=$1, name=$2, description=$3, base_price=$4
		WHERE  id=$5 AND deleted_at IS NULL`,
		e.OrganizationId, e.Name, e.Description, e.BasePrice, e.Id,
	)
	return err
}

func (r *RoomTypeRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.RoomType, error) {
	e := &entity.RoomType{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, name, description, base_price, deleted_at
		FROM   room_types
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.Name, &e.Description, &e.BasePrice, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("roomtype repository: find by id: %w", err)
	}
	return e, nil
}

func (r *RoomTypeRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.RoomType, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, name, description, base_price, deleted_at
		FROM   room_types
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("roomtype repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.RoomType
	for rows.Next() {
		e := &entity.RoomType{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.Name, &e.Description, &e.BasePrice, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *RoomTypeRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE room_types SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
