// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/roomtype/entity"
)

// RoomTypeRepository is the contract for persisting RoomType aggregates.
type RoomTypeRepository interface {
	// Save persists a RoomType entity.
	Save(ctx context.Context, e *entity.RoomType) error

	// FindByID retrieves a RoomType by its primary key.
	FindByID(ctx context.Context, id string) (*entity.RoomType, error)

	// FindAll retrieves a paginated list of RoomType entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.RoomType, error)

	// Delete removes a RoomType by its primary key.
	Delete(ctx context.Context, id string) error
}
