// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"
	"github.com/epmp/backend/internal/pkg/errs"
	"time"

	"github.com/epmp/backend/internal/modules/property/dto"
	"github.com/epmp/backend/internal/modules/property/entity"
	"github.com/jackc/pgx/v5/pgxpool"
)

// PropertyRepositoryImpl implements PropertyRepository using PostgreSQL.
type PropertyRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewPropertyRepositoryImpl creates a new PropertyRepositoryImpl.
func NewPropertyRepositoryImpl(db *pgxpool.Pool) *PropertyRepositoryImpl {
	return &PropertyRepositoryImpl{db: db}
}

// Ensure PropertyRepositoryImpl implements domain repository interface.
var _ PropertyRepository = (*PropertyRepositoryImpl)(nil)

func (r *PropertyRepositoryImpl) Save(ctx context.Context, e *entity.Property) error {
	var orgID interface{}
	if e.OrganizationId != "" {
		orgID = e.OrganizationId
	}

	if e.Id == "" {
		// INSERT — caller must pre-set e.Id with uid.New()
		return fmt.Errorf("property repository: save: id must be pre-set by caller (use uid.New())")
	}

	// Check if record exists to decide INSERT vs UPDATE
	var exists bool
	err := r.db.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM properties WHERE id=$1)`, e.Id).Scan(&exists)
	if err != nil {
		return fmt.Errorf("property repository: save: check exists: %w", err)
	}

	if !exists {
		// INSERT with caller-provided ULID
		err = r.db.QueryRow(ctx, `
			INSERT INTO properties (id, organization_id, name, description, address, property_type, is_active)
			VALUES ($1, $2, $3, $4, $5, $6, $7)
			RETURNING created_at, updated_at`,
			e.Id, orgID, e.Name, e.Description, e.Address, e.PropertyType, e.IsActive,
		).Scan(&e.CreatedAt, &e.UpdatedAt)
		return err
	}
	// UPDATE
	_, err = r.db.Exec(ctx, `
		UPDATE properties
		SET    organization_id=$1, name=$2, description=$3, address=$4, property_type=$5, is_active=$6
		WHERE  id=$7 AND deleted_at IS NULL`,
		orgID, e.Name, e.Description, e.Address, e.PropertyType, e.IsActive, e.Id,
	)
	return err
}

func (r *PropertyRepositoryImpl) FindByID(ctx context.Context, id, orgID string) (*entity.Property, error) {
	e := &entity.Property{}
	var orgIDPtr *string
	query := `
		SELECT organization_id, id, name, description, address, property_type, is_active, created_at, updated_at, deleted_at
		FROM   properties
		WHERE  id = $1 AND deleted_at IS NULL`
	args := []interface{}{id}
	if orgID != "" {
		query += ` AND organization_id = $2`
		args = append(args, orgID)
	}
	err := r.db.QueryRow(ctx, query, args...).Scan(&orgIDPtr, &e.Id, &e.Name, &e.Description, &e.Address, &e.PropertyType, &e.IsActive, &e.CreatedAt, &e.UpdatedAt, &e.DeletedAt)
	if orgIDPtr != nil {
		e.OrganizationId = *orgIDPtr
	}

	if err != nil {
		return nil, fmt.Errorf("property repository: find by id: %w", err)
	}
	return e, nil
}

func (r *PropertyRepositoryImpl) FindAll(ctx context.Context, limit, offset int, search, orgID string) ([]*entity.Property, error) {
	query := `
		SELECT organization_id, id, name, description, address, property_type, is_active, created_at, updated_at, deleted_at
		FROM   properties
		WHERE  deleted_at IS NULL`
	args := []interface{}{}
	argIdx := 1

	if search != "" {
		query += fmt.Sprintf(` AND name ILIKE $%d`, argIdx)
		args = append(args, "%"+search+"%")
		argIdx++
	}
	if orgID != "" {
		query += fmt.Sprintf(` AND organization_id = $%d`, argIdx)
		args = append(args, orgID)
		argIdx++
	}

	query += fmt.Sprintf(` ORDER BY created_at DESC LIMIT $%d OFFSET $%d`, argIdx, argIdx+1)
	args = append(args, limit, offset)

	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("property repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Property
	for rows.Next() {
		e := &entity.Property{}
		var orgIDPtr *string
		if err := rows.Scan(&orgIDPtr, &e.Id, &e.Name, &e.Description, &e.Address, &e.PropertyType, &e.IsActive, &e.CreatedAt, &e.UpdatedAt, &e.DeletedAt); err != nil {
			return nil, err
		}
		if orgIDPtr != nil {
			e.OrganizationId = *orgIDPtr
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

// Count returns the total number of non-deleted properties.
func (r *PropertyRepositoryImpl) Count(ctx context.Context, search, orgID string) (int64, error) {
	query := `SELECT COUNT(*) FROM properties WHERE deleted_at IS NULL`
	args := []interface{}{}
	argIdx := 1

	if search != "" {
		query += fmt.Sprintf(` AND name ILIKE $%d`, argIdx)
		args = append(args, "%"+search+"%")
		argIdx++
	}
	if orgID != "" {
		query += fmt.Sprintf(` AND organization_id = $%d`, argIdx)
		args = append(args, orgID)
	}

	var count int64
	err := r.db.QueryRow(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("property repository: count: %w", err)
	}
	return count, nil
}

func (r *PropertyRepositoryImpl) Delete(ctx context.Context, id, orgID string) error {
	tag, err := r.db.Exec(ctx, `
		UPDATE properties SET deleted_at = now() WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`, id, orgID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return errs.ErrNotFound
	}
	return nil
}

func (r *PropertyRepositoryImpl) FindStaffByPropertyID(ctx context.Context, propertyID, orgID string) ([]*dto.PropertyStaffResponse, error) {
	rows, err := r.db.Query(ctx, `
		SELECT pur.id, pur.property_id, pur.user_id, COALESCE(u.name, ''), COALESCE(u.email, ''),
		       pur.role_id, COALESCE(ro.name, ''), COALESCE(ro.is_system, false), pur.created_at
		FROM   property_user_roles pur
		JOIN   users u ON u.id = pur.user_id
		JOIN   roles ro ON ro.id = pur.role_id
		WHERE  pur.property_id = $1 AND pur.organization_id = $2
		ORDER  BY pur.created_at DESC`,
		propertyID, orgID,
	)
	if err != nil {
		return nil, fmt.Errorf("property repository: find staff: %w", err)
	}
	defer rows.Close()

	var list []*dto.PropertyStaffResponse
	for rows.Next() {
		s := &dto.PropertyStaffResponse{}
		if err := rows.Scan(&s.Id, &s.PropertyId, &s.UserId, &s.UserName, &s.UserEmail, &s.RoleId, &s.RoleName, &s.IsSystem, &s.CreatedAt); err != nil {
			return nil, err
		}
		list = append(list, s)
	}
	return list, rows.Err()
}

func (r *PropertyRepositoryImpl) AssignStaff(ctx context.Context, orgID, propertyID, userID, roleID string) (*dto.PropertyStaffResponse, error) {
	var id string
	var createdAt time.Time
	err := r.db.QueryRow(ctx, `
		INSERT INTO property_user_roles (organization_id, property_id, user_id, role_id)
		VALUES ($1, $2, $3, $4)
		ON CONFLICT (property_id, user_id, role_id)
		DO UPDATE SET updated_at = now()
		RETURNING id, created_at`,
		orgID, propertyID, userID, roleID,
	).Scan(&id, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("property repository: assign staff: %w", err)
	}

	var userName, userEmail, roleName string
	var isSystem bool
	_ = r.db.QueryRow(ctx, `SELECT name, email FROM users WHERE id = $1`, userID).Scan(&userName, &userEmail)
	_ = r.db.QueryRow(ctx, `SELECT name, is_system FROM roles WHERE id = $1`, roleID).Scan(&roleName, &isSystem)

	return &dto.PropertyStaffResponse{
		Id:         id,
		PropertyId: propertyID,
		UserId:     userID,
		UserName:   userName,
		UserEmail:  userEmail,
		RoleId:     roleID,
		RoleName:   roleName,
		IsSystem:   isSystem,
		CreatedAt:  createdAt,
	}, nil
}

func (r *PropertyRepositoryImpl) RemoveStaff(ctx context.Context, propertyID, userID, roleID, orgID string) error {
	_, err := r.db.Exec(ctx, `
		DELETE FROM property_user_roles
		WHERE property_id = $1 AND user_id = $2 AND role_id = $3 AND organization_id = $4`,
		propertyID, userID, roleID, orgID,
	)
	return err
}
