// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/property/entity"
)

// PropertyRepository is the contract for persisting Property aggregates.
type PropertyRepository interface {
	// Save persists a Property entity.
	Save(ctx context.Context, e *entity.Property) error

	// FindByID retrieves a Property by its primary key.
	// If orgID is non-empty, the result must belong to that organization.
	FindByID(ctx context.Context, id, orgID string) (*entity.Property, error)

	// FindAll retrieves a paginated list of Property entities.
	// If orgID is non-empty, results are filtered to that organization.
	FindAll(ctx context.Context, limit, offset int, search, orgID string) ([]*entity.Property, error)

	// Count returns the total number of non-deleted Properties.
	// If orgID is non-empty, count is filtered to that organization.
	Count(ctx context.Context, search, orgID string) (int64, error)

	// Delete removes a Property by its primary key.
	Delete(ctx context.Context, id string) error
}
