// Code generated by epmp-sdk. DO NOT EDIT.

package service

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/roomtype/dto"
	"github.com/epmp/backend/internal/modules/roomtype/entity"
	"github.com/epmp/backend/internal/modules/roomtype/repository"
)

// RoomTypeService implements the application layer for RoomType.
type RoomTypeService struct {
	repo repository.RoomTypeRepository
}

// NewRoomTypeService creates a new RoomTypeService.
func NewRoomTypeService(repo repository.RoomTypeRepository) *RoomTypeService {
	return &RoomTypeService{repo: repo}
}

func (s *RoomTypeService) Create(ctx context.Context, req *dto.CreateRoomTypeRequest) (*dto.RoomTypeResponse, error) {
	e := entity.NewRoomType()
	e.OrganizationId = req.OrganizationId
	e.Name = req.Name
	e.Description = req.Description
	e.BasePrice = req.BasePrice

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("roomtype service: create: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *RoomTypeService) GetByID(ctx context.Context, id string) (*dto.RoomTypeResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("roomtype service: get by id: %w", err)
	}
	return s.toResponse(e), nil
}

func (s *RoomTypeService) List(ctx context.Context, page, perPage int) (*dto.RoomTypeListResponse, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 {
		perPage = 20
	}
	offset := (page - 1) * perPage

	items, err := s.repo.FindAll(ctx, perPage, offset)
	if err != nil {
		return nil, fmt.Errorf("roomtype service: list: %w", err)
	}

	data := make([]dto.RoomTypeResponse, 0, len(items))
	for _, e := range items {
		data = append(data, *s.toResponse(e))
	}

	return &dto.RoomTypeListResponse{
		Data:    data,
		Page:    page,
		PerPage: perPage,
	}, nil
}

func (s *RoomTypeService) Update(ctx context.Context, id string, req *dto.UpdateRoomTypeRequest) (*dto.RoomTypeResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("roomtype service: update: find: %w", err)
	}
	e.OrganizationId = req.OrganizationId
	e.Name = req.Name
	e.Description = req.Description
	e.BasePrice = req.BasePrice

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("roomtype service: update: save: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *RoomTypeService) Delete(ctx context.Context, id string) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("roomtype service: delete: %w", err)
	}
	return nil
}

func (s *RoomTypeService) toResponse(e *entity.RoomType) *dto.RoomTypeResponse {
	return &dto.RoomTypeResponse{
		OrganizationId: e.OrganizationId,
		Id: e.Id,
		Name: e.Name,
		Description: e.Description,
		BasePrice: e.BasePrice,
	}
}
