// Code generated by epmp-sdk. DO NOT EDIT.

package bed

import (
	"github.com/epmp/backend/internal/modules/bed/delivery/http"
	"github.com/epmp/backend/internal/modules/bed/repository"
	"github.com/epmp/backend/internal/modules/bed/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all Bed dependencies.
type Module struct {
	Handler *http.BedHandler
}

// NewModule creates and wires all Bed dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.BedRepository = repository.NewBedRepositoryImpl(db)
	svc := service.NewBedService(repo)
	handler := http.NewBedHandler(svc)

	log.Info().Str("module", "bed").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all Bed routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/beds")
	http.RegisterBedRoutes(g, m.Handler)
}
