// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  createFacilitySchema,
  type CreateFacilityFormData,
} from "../schema";

interface FacilityFormProps {
  onSubmit: (data: CreateFacilityFormData) => void;
  defaultValues?: Partial<CreateFacilityFormData>;
  isSubmitting?: boolean;
}

export function FacilityForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: FacilityFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateFacilityFormData>({
    resolver: zodResolver(createFacilitySchema),
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="organization_id">OrganizationId</Label>
        <Input
          id="organization_id"
          {...register("organization_id")}
        />
        {errors.organization_id && (
          <p className="text-sm text-red-500">{errors.organization_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="property_id">PropertyId</Label>
        <Input
          id="property_id"
          {...register("property_id")}
        />
        {errors.property_id && (
          <p className="text-sm text-red-500">{errors.property_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="name">Name</Label>
        <Input
          id="name"
          {...register("name")}
        />
        {errors.name && (
          <p className="text-sm text-red-500">{errors.name.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="description">Description</Label>
        <Input
          id="description"
          {...register("description")}
        />
        {errors.description && (
          <p className="text-sm text-red-500">{errors.description.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting}>
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
