// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { usePropertys } from "@/features/property/hooks";
import {
  createFacilitySchema,
  type CreateFacilityFormData,
} from "../schema";

interface FacilityFormProps {
  onSubmit: (data: CreateFacilityFormData) => void;
  defaultValues?: Partial<CreateFacilityFormData>;
  isSubmitting?: boolean;
}

export function FacilityForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: FacilityFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateFacilityFormData>({
    resolver: zodResolver(createFacilitySchema),
    defaultValues,
  });

  const { data: propertiesData } = usePropertys({ per_page: 100 });
  const properties = propertiesData?.data || [];

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      <div className="space-y-2">
        <Label htmlFor="property_id">Property</Label>
        <select
          id="property_id"
          {...register("property_id")}
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm bg-white text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange"
        >
          <option value="">Select a property...</option>
          {properties.map((p) => (
            <option key={p.id} value={p.id}>
              {p.name}
            </option>
          ))}
        </select>
        {errors.property_id && (
          <p className="text-xs text-red-600 mt-1">{errors.property_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="name">Facility Name</Label>
        <Input
          id="name"
          placeholder="e.g. Swimming Pool, Gym, Meeting Room"
          {...register("name")}
        />
        {errors.name && (
          <p className="text-xs text-red-600 mt-1">{errors.name.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="description">Description</Label>
        <Input
          id="description"
          placeholder="Facility details / rules"
          {...register("description")}
        />
        {errors.description && (
          <p className="text-xs text-red-600 mt-1">{errors.description.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting} className="bg-orange hover:bg-orange/90 text-white w-full sm:w-auto">
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
