// Code generated by epmp-sdk. DO NOT EDIT.

package entity

import "time"

// Property is the domain entity for property.
type Property struct {
	OrganizationId string     `json:"organization_id"`
	Id             string     `json:"id"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	Address        string     `json:"address"`
	PropertyType   string     `json:"property_type"`
	IsActive       bool       `json:"is_active"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at,omitempty"`
}

// NewProperty creates a new Property instance.
func NewProperty() *Property {
	return &Property{}
}
