// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  WorkOrder,
  WorkOrderListResponse,
  CreateWorkOrderRequest,
  UpdateWorkOrderRequest,
  WorkOrderQueryParams,
} from "../types";

const BASE_PATH = "/work_orders";
export async function fetchWorkOrders(params?: WorkOrderQueryParams): Promise<WorkOrderListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: WorkOrderListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchWorkOrderById(id: string): Promise<WorkOrder> {
  const res = await api.get<{ success: boolean; data: WorkOrder }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createWorkOrder(data: CreateWorkOrderRequest): Promise<WorkOrder> {
  const res = await api.post<{ success: boolean; data: WorkOrder }>(BASE_PATH, data);
  return res.data;
}
export async function updateWorkOrder(id: string, data: UpdateWorkOrderRequest): Promise<WorkOrder> {
  const res = await api.put<{ success: boolean; data: WorkOrder }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteWorkOrder(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
