// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateFacility } from "../hooks";
import { FacilityForm } from "../components/FacilityForm";
import type { CreateFacilityFormData } from "../schema";

export function FacilityCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateFacility();

  const handleSubmit = (data: CreateFacilityFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/facility"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New Facility</h1>
      <FacilityForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
