// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useQuery,
  useMutation,
  useQueryClient,
} from "@tanstack/react-query";
import {
  fetchFloors,
  fetchFloorById,
  createFloor,
  updateFloor,
  deleteFloor,
} from "../api";
import type {
  FloorQueryParams,
  CreateFloorRequest,
  UpdateFloorRequest,
} from "../types";

const QUERY_KEY = "floors";
export function useFloors(params?: FloorQueryParams) {
  return useQuery({
    queryKey: [QUERY_KEY, params],
    queryFn: () => fetchFloors(params),
  });
}
export function useFloor(id: string | undefined) {
  return useQuery({
    queryKey: [QUERY_KEY, id],
    queryFn: () => fetchFloorById(id!),
    enabled: !!id,
  });
}
export function useCreateFloor() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateFloorRequest) => createFloor(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useUpdateFloor() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateFloorRequest }) =>
      updateFloor(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
export function useDeleteFloor() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteFloor(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [QUERY_KEY] });
    },
  });
}
