// Code generated by epmp-sdk. DO NOT EDIT.

export interface Technician {
  organization_id: string;
  id: string;
  name: string;
  phone: string;
  specialty: string;
  deleted_at?: string;
  created_at: string;
  updated_at: string;
}

export interface TechnicianListResponse {
  data: Technician[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface CreateTechnicianRequest {
  name: string;
  phone: string;
  specialty: string;
}

export interface UpdateTechnicianRequest {
  name: string;
  phone: string;
  specialty: string;
}

export interface TechnicianQueryParams {
  page?: number;
  per_page?: number;
  search?: string;
  name?: string;
}
