// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  createTechnicianSchema,
  type CreateTechnicianFormData,
} from "../schema";

interface TechnicianFormProps {
  onSubmit: (data: CreateTechnicianFormData) => void;
  defaultValues?: Partial<CreateTechnicianFormData>;
  isSubmitting?: boolean;
}

export function TechnicianForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: TechnicianFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateTechnicianFormData>({
    resolver: zodResolver(createTechnicianSchema),
    defaultValues,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      <div className="space-y-2">
        <Label htmlFor="name">Name</Label>
        <Input
          id="name"
          {...register("name")}
        />
        {errors.name && (
          <p className="text-xs text-red-600 mt-1">{errors.name.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="phone">Phone</Label>
        <Input
          id="phone"
          {...register("phone")}
        />
        {errors.phone && (
          <p className="text-xs text-red-600 mt-1">{errors.phone.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="specialty">Specialty</Label>
        <Input
          id="specialty"
          {...register("specialty")}
        />
        {errors.specialty && (
          <p className="text-xs text-red-600 mt-1">{errors.specialty.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting} className="bg-orange hover:bg-orange/90 text-white w-full sm:w-auto">
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
