// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  AssetAssignment,
  AssetAssignmentListResponse,
  CreateAssetAssignmentRequest,
  UpdateAssetAssignmentRequest,
  AssetAssignmentQueryParams,
} from "../types";

const BASE_PATH = "/api/asset_assignments";
export async function fetchAssetAssignments(params?: AssetAssignmentQueryParams): Promise<AssetAssignmentListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<AssetAssignmentListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchAssetAssignmentById(id: string): Promise<AssetAssignment> {
  return api.get<AssetAssignment>(`${BASE_PATH}/${id}`);
}
export async function createAssetAssignment(data: CreateAssetAssignmentRequest): Promise<AssetAssignment> {
  return api.post<AssetAssignment>(BASE_PATH, data);
}
export async function updateAssetAssignment(id: string, data: UpdateAssetAssignmentRequest): Promise<AssetAssignment> {
  return api.put<AssetAssignment>(`${BASE_PATH}/${id}`, data);
}
export async function deleteAssetAssignment(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
