// Code generated by epmp-sdk. DO NOT EDIT.

package tenantcontact

import (
	"github.com/epmp/backend/internal/modules/tenantcontact/delivery/http"
	"github.com/epmp/backend/internal/modules/tenantcontact/repository"
	"github.com/epmp/backend/internal/modules/tenantcontact/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all TenantContact dependencies.
type Module struct {
	Handler *http.TenantContactHandler
}

// NewModule creates and wires all TenantContact dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.TenantContactRepository = repository.NewTenantContactRepositoryImpl(db)
	svc := service.NewTenantContactService(repo)
	handler := http.NewTenantContactHandler(svc)

	log.Info().Str("module", "tenantcontact").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all TenantContact routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/tenant_contacts")
	http.RegisterTenantContactRoutes(g, m.Handler)
}
