// Code generated by epmp-sdk. DO NOT EDIT.

package building

import (
	"github.com/epmp/backend/internal/modules/building/delivery/http"
	"github.com/epmp/backend/internal/modules/building/repository"
	"github.com/epmp/backend/internal/modules/building/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all Building dependencies.
type Module struct {
	Handler *http.BuildingHandler
}

// NewModule creates and wires all Building dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.BuildingRepository = repository.NewBuildingRepositoryImpl(db)
	svc := service.NewBuildingService(repo)
	handler := http.NewBuildingHandler(svc)

	log.Info().Str("module", "building").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all Building routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/buildings")
	http.RegisterBuildingRoutes(g, m.Handler)
}
