// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Penalty,
  PenaltyListResponse,
  CreatePenaltyRequest,
  UpdatePenaltyRequest,
  PenaltyQueryParams,
} from "../types";

const BASE_PATH = "/penalties";
export async function fetchPenaltys(params?: PenaltyQueryParams): Promise<PenaltyListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: PenaltyListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchPenaltyById(id: string): Promise<Penalty> {
  const res = await api.get<{ success: boolean; data: Penalty }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createPenalty(data: CreatePenaltyRequest): Promise<Penalty> {
  const res = await api.post<{ success: boolean; data: Penalty }>(BASE_PATH, data);
  return res.data;
}
export async function updatePenalty(id: string, data: UpdatePenaltyRequest): Promise<Penalty> {
  const res = await api.put<{ success: boolean; data: Penalty }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deletePenalty(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
