// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Penalty,
  PenaltyListResponse,
  CreatePenaltyRequest,
  UpdatePenaltyRequest,
  PenaltyQueryParams,
} from "../types";

const BASE_PATH = "/api/penalties";
export async function fetchPenaltys(params?: PenaltyQueryParams): Promise<PenaltyListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<PenaltyListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchPenaltyById(id: string): Promise<Penalty> {
  return api.get<Penalty>(`${BASE_PATH}/${id}`);
}
export async function createPenalty(data: CreatePenaltyRequest): Promise<Penalty> {
  return api.post<Penalty>(BASE_PATH, data);
}
export async function updatePenalty(id: string, data: UpdatePenaltyRequest): Promise<Penalty> {
  return api.put<Penalty>(`${BASE_PATH}/${id}`, data);
}
export async function deletePenalty(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
