// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/zone/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// ZoneRepositoryImpl implements ZoneRepository using PostgreSQL.
type ZoneRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewZoneRepositoryImpl creates a new ZoneRepositoryImpl.
func NewZoneRepositoryImpl(db *pgxpool.Pool) *ZoneRepositoryImpl {
	return &ZoneRepositoryImpl{db: db}
}

// Ensure ZoneRepositoryImpl implements domain repository interface.
var _ ZoneRepository = (*ZoneRepositoryImpl)(nil)

func (r *ZoneRepositoryImpl) Save(ctx context.Context, e *entity.Zone) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO zones (organization_id, building_id, floor, name)
			VALUES ($1, $2, $3, $4)
			RETURNING id`,
			e.OrganizationId, e.BuildingId, e.Floor, e.Name,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE zones
		SET    organization_id=$1, building_id=$2, floor=$3, name=$4
		WHERE  id=$5 AND deleted_at IS NULL`,
		e.OrganizationId, e.BuildingId, e.Floor, e.Name, e.Id,
	)
	return err
}

func (r *ZoneRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Zone, error) {
	e := &entity.Zone{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, building_id, floor, name, deleted_at
		FROM   zones
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.BuildingId, &e.Floor, &e.Name, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("zone repository: find by id: %w", err)
	}
	return e, nil
}

func (r *ZoneRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Zone, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, building_id, floor, name, deleted_at
		FROM   zones
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("zone repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Zone
	for rows.Next() {
		e := &entity.Zone{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.BuildingId, &e.Floor, &e.Name, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *ZoneRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE zones SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
