// Code generated by epmp-sdk. DO NOT EDIT.

package billing

import (
	"github.com/epmp/backend/internal/modules/billing/delivery/http"
	"github.com/epmp/backend/internal/modules/billing/repository"
	"github.com/epmp/backend/internal/modules/billing/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all Invoice dependencies.
type Module struct {
	Handler *http.InvoiceHandler
}

// NewModule creates and wires all Invoice dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.InvoiceRepository = repository.NewInvoiceRepositoryImpl(db)
	svc := service.NewInvoiceService(repo)
	handler := http.NewInvoiceHandler(svc)

	log.Info().Str("module", "billing").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all Invoice routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/invoices")
	http.RegisterInvoiceRoutes(g, m.Handler)
}
