// Code generated by epmp-sdk. DO NOT EDIT.

package organization

import (
	"github.com/epmp/backend/internal/modules/organization/delivery/http"
	"github.com/epmp/backend/internal/modules/organization/repository"
	"github.com/epmp/backend/internal/modules/organization/service"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/labstack/echo/v4"
	"github.com/rs/zerolog"
)

// Module wires together all Organization dependencies.
type Module struct {
	Handler *http.OrganizationHandler
}

// NewModule creates and wires all Organization dependencies.
func NewModule(db *pgxpool.Pool, log zerolog.Logger) *Module {
	var repo repository.OrganizationRepository = repository.NewOrganizationRepositoryImpl(db)
	svc := service.NewOrganizationService(repo)
	handler := http.NewOrganizationHandler(svc)

	log.Info().Str("module", "organization").Msg("module initialized")

	return &Module{
		Handler: handler,
	}
}

// RegisterRoutes registers all Organization routes on the given Echo instance.
func (m *Module) RegisterRoutes(e *echo.Group) {
	g := e.Group("/api/organizations")
	http.RegisterOrganizationRoutes(g, m.Handler)
}
