// Code generated by epmp-sdk. DO NOT EDIT.

package service

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/tenantdocument/dto"
	"github.com/epmp/backend/internal/modules/tenantdocument/entity"
	"github.com/epmp/backend/internal/modules/tenantdocument/repository"
)

// TenantDocumentService implements the application layer for TenantDocument.
type TenantDocumentService struct {
	repo repository.TenantDocumentRepository
}

// NewTenantDocumentService creates a new TenantDocumentService.
func NewTenantDocumentService(repo repository.TenantDocumentRepository) *TenantDocumentService {
	return &TenantDocumentService{repo: repo}
}

func (s *TenantDocumentService) Create(ctx context.Context, req *dto.CreateTenantDocumentRequest) (*dto.TenantDocumentResponse, error) {
	e := entity.NewTenantDocument()
	e.OrganizationId = req.OrganizationId
	e.TenantId = req.TenantId
	e.DocumentType = req.DocumentType
	e.FileUrl = req.FileUrl

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("tenantdocument service: create: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *TenantDocumentService) GetByID(ctx context.Context, id string) (*dto.TenantDocumentResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("tenantdocument service: get by id: %w", err)
	}
	return s.toResponse(e), nil
}

func (s *TenantDocumentService) List(ctx context.Context, page, perPage int) (*dto.TenantDocumentListResponse, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 {
		perPage = 20
	}
	offset := (page - 1) * perPage

	items, err := s.repo.FindAll(ctx, perPage, offset)
	if err != nil {
		return nil, fmt.Errorf("tenantdocument service: list: %w", err)
	}

	data := make([]dto.TenantDocumentResponse, 0, len(items))
	for _, e := range items {
		data = append(data, *s.toResponse(e))
	}

	return &dto.TenantDocumentListResponse{
		Data:    data,
		Page:    page,
		PerPage: perPage,
	}, nil
}

func (s *TenantDocumentService) Update(ctx context.Context, id string, req *dto.UpdateTenantDocumentRequest) (*dto.TenantDocumentResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("tenantdocument service: update: find: %w", err)
	}
	e.OrganizationId = req.OrganizationId
	e.TenantId = req.TenantId
	e.DocumentType = req.DocumentType
	e.FileUrl = req.FileUrl

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("tenantdocument service: update: save: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *TenantDocumentService) Delete(ctx context.Context, id string) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("tenantdocument service: delete: %w", err)
	}
	return nil
}

func (s *TenantDocumentService) toResponse(e *entity.TenantDocument) *dto.TenantDocumentResponse {
	return &dto.TenantDocumentResponse{
		OrganizationId: e.OrganizationId,
		Id: e.Id,
		TenantId: e.TenantId,
		DocumentType: e.DocumentType,
		FileUrl: e.FileUrl,
	}
}
