// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useContract, useDeleteContract } from "../hooks";

export function ContractDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useContract(id);
  const deleteMutation = useDeleteContract();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this contract?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/contract"),
    });
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Contract Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/contract")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/contract/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">OrganizationId</dt>
          <dd className="text-sm">{String(data.organization_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Id</dt>
          <dd className="text-sm">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">ReservationId</dt>
          <dd className="text-sm">{String(data.reservation_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">TenantId</dt>
          <dd className="text-sm">{String(data.tenant_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">PropertyId</dt>
          <dd className="text-sm">{String(data.property_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">RoomId</dt>
          <dd className="text-sm">{String(data.room_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Status</dt>
          <dd className="text-sm">{String(data.status ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">StartDate</dt>
          <dd className="text-sm">{String(data.start_date ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">EndDate</dt>
          <dd className="text-sm">{String(data.end_date ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">MonthlyRent</dt>
          <dd className="text-sm">{String(data.monthly_rent ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">DepositAmount</dt>
          <dd className="text-sm">{String(data.deposit_amount ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Terms</dt>
          <dd className="text-sm">{String(data.terms ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
