// Code generated by epmp-sdk. DO NOT EDIT.

package service

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/assetinspection/dto"
	"github.com/epmp/backend/internal/modules/assetinspection/entity"
	"github.com/epmp/backend/internal/modules/assetinspection/repository"
)

// AssetInspectionService implements the application layer for AssetInspection.
type AssetInspectionService struct {
	repo repository.AssetInspectionRepository
}

// NewAssetInspectionService creates a new AssetInspectionService.
func NewAssetInspectionService(repo repository.AssetInspectionRepository) *AssetInspectionService {
	return &AssetInspectionService{repo: repo}
}

func (s *AssetInspectionService) Create(ctx context.Context, req *dto.CreateAssetInspectionRequest) (*dto.AssetInspectionResponse, error) {
	e := entity.NewAssetInspection()
	e.OrganizationId = req.OrganizationId
	e.AssetId = req.AssetId
	e.InspectionDate = req.InspectionDate
	e.Condition = req.Condition
	e.Notes = req.Notes

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("assetinspection service: create: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *AssetInspectionService) GetByID(ctx context.Context, id string) (*dto.AssetInspectionResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("assetinspection service: get by id: %w", err)
	}
	return s.toResponse(e), nil
}

func (s *AssetInspectionService) List(ctx context.Context, page, perPage int) (*dto.AssetInspectionListResponse, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 {
		perPage = 20
	}
	offset := (page - 1) * perPage

	items, err := s.repo.FindAll(ctx, perPage, offset)
	if err != nil {
		return nil, fmt.Errorf("assetinspection service: list: %w", err)
	}

	data := make([]dto.AssetInspectionResponse, 0, len(items))
	for _, e := range items {
		data = append(data, *s.toResponse(e))
	}

	return &dto.AssetInspectionListResponse{
		Data:    data,
		Page:    page,
		PerPage: perPage,
	}, nil
}

func (s *AssetInspectionService) Update(ctx context.Context, id string, req *dto.UpdateAssetInspectionRequest) (*dto.AssetInspectionResponse, error) {
	e, err := s.repo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("assetinspection service: update: find: %w", err)
	}
	e.OrganizationId = req.OrganizationId
	e.AssetId = req.AssetId
	e.InspectionDate = req.InspectionDate
	e.Condition = req.Condition
	e.Notes = req.Notes

	if err := s.repo.Save(ctx, e); err != nil {
		return nil, fmt.Errorf("assetinspection service: update: save: %w", err)
	}

	return s.toResponse(e), nil
}

func (s *AssetInspectionService) Delete(ctx context.Context, id string) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		return fmt.Errorf("assetinspection service: delete: %w", err)
	}
	return nil
}

func (s *AssetInspectionService) toResponse(e *entity.AssetInspection) *dto.AssetInspectionResponse {
	return &dto.AssetInspectionResponse{
		OrganizationId: e.OrganizationId,
		Id: e.Id,
		AssetId: e.AssetId,
		InspectionDate: e.InspectionDate,
		Condition: e.Condition,
		Notes: e.Notes,
	}
}
