// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/adjustment/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// AdjustmentRepositoryImpl implements AdjustmentRepository using PostgreSQL.
type AdjustmentRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewAdjustmentRepositoryImpl creates a new AdjustmentRepositoryImpl.
func NewAdjustmentRepositoryImpl(db *pgxpool.Pool) *AdjustmentRepositoryImpl {
	return &AdjustmentRepositoryImpl{db: db}
}

// Ensure AdjustmentRepositoryImpl implements domain repository interface.
var _ AdjustmentRepository = (*AdjustmentRepositoryImpl)(nil)

func (r *AdjustmentRepositoryImpl) Save(ctx context.Context, e *entity.Adjustment) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO adjustments (organization_id, invoice_id, adjustment_type, amount, adjustment_date, reason)
			VALUES ($1, $2, $3, $4, $5, $6)
			RETURNING id`,
			e.OrganizationId, e.InvoiceId, e.AdjustmentType, e.Amount, e.AdjustmentDate, e.Reason,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE adjustments
		SET    organization_id=$1, invoice_id=$2, adjustment_type=$3, amount=$4, adjustment_date=$5, reason=$6
		WHERE  id=$7 AND deleted_at IS NULL`,
		e.OrganizationId, e.InvoiceId, e.AdjustmentType, e.Amount, e.AdjustmentDate, e.Reason, e.Id,
	)
	return err
}

func (r *AdjustmentRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Adjustment, error) {
	e := &entity.Adjustment{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, invoice_id, adjustment_type, amount, adjustment_date, reason, deleted_at
		FROM   adjustments
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.InvoiceId, &e.AdjustmentType, &e.Amount, &e.AdjustmentDate, &e.Reason, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("adjustment repository: find by id: %w", err)
	}
	return e, nil
}

func (r *AdjustmentRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Adjustment, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, invoice_id, adjustment_type, amount, adjustment_date, reason, deleted_at
		FROM   adjustments
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("adjustment repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.Adjustment
	for rows.Next() {
		e := &entity.Adjustment{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.InvoiceId, &e.AdjustmentType, &e.Amount, &e.AdjustmentDate, &e.Reason, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *AdjustmentRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE adjustments SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
