// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const assetSchema = z.object({
  organization_id: z.string(),
  id: z.string(),
  property_id: z.string(),
  name: z.string().max(100),
  category: z.string().max(100),
  status: z.enum(["Available", "Assigned", "Maintenance", "Disposed"]),
  purchase_price: z.number(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createAssetSchema = assetSchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export const updateAssetSchema = createAssetSchema.partial();

export type AssetFormData = z.infer<typeof assetSchema>;
export type CreateAssetFormData = z.infer<typeof createAssetSchema>;
export type UpdateAssetFormData = z.infer<typeof updateAssetSchema>;
