// Code generated by epmp-sdk. DO NOT EDIT.

import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  createColumnHelper,
} from "@tanstack/react-table";
import type { Deposit } from "../types";
import { useContracts } from "../../contract/hooks";
import { useTenants } from "../../tenant/hooks";

import { formatDate } from "@/utils/date";
import { formatCurrency } from "@/utils/currency";

const columnHelper = createColumnHelper<Deposit>();

interface DepositTableProps {
  data: Deposit[];
  onRowClick?: (row: Deposit) => void;
}

export function DepositTable({ data, onRowClick }: DepositTableProps) {
  const { data: contractsData } = useContracts({ per_page: 100 });
  const { data: tenantsData } = useTenants({ per_page: 100 });
  const contractsMap = new Map(
    (Array.isArray(contractsData?.data) ? contractsData.data : Array.isArray(contractsData) ? contractsData : [])
      .map((item: any) => [item.id, `Kontrak #${item.id.slice(0, 8)}`])
  );
  const tenantsMap = new Map(
    (Array.isArray(tenantsData?.data) ? tenantsData.data : Array.isArray(tenantsData) ? tenantsData : [])
      .map((item: any) => [item.id, item.full_name])
  );

  const columns = [
    columnHelper.accessor("tenant_id", {
      header: "Penyewa (Tenant)",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        const name = tenantsMap.get(id);
        return (
          <div>
            <span className="font-semibold text-slate-800">{name || 'Penyewa'}</span>
            <p className="text-[11px] text-slate-400 font-mono">#{id.slice(0, 8)}</p>
          </div>
        );
      },
    }),
    columnHelper.accessor("contract_id", {
      header: "Kontrak",
      cell: (info) => {
        const id = info.getValue() as string;
        if (!id) return <span className="text-slate-400">—</span>;
        return (
          <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-slate-100 text-slate-700">
            {contractsMap.get(id) || `#${id.slice(0, 8)}`}
          </span>
        );
      },
    }),
    columnHelper.accessor("amount", {
      header: "Jumlah Deposit",
      cell: (info) => {
        const val = info.getValue();
        const row = info.row.original;
        return (
          <span className="font-bold text-slate-900">
            {formatCurrency(val, (row as any).currency || "IDR")}
          </span>
        );
      },
    }),
    columnHelper.accessor("status", {
      header: "Status",
      cell: (info) => {
        const val = (info.getValue() as string) || "Holding";
        const isRefunded = val.toLowerCase() === "refunded";
        return (
          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold ${
            isRefunded ? 'bg-slate-100 text-slate-600' : 'bg-blue-100 text-blue-700'
          }`}>
            {val}
          </span>
        );
      },
    }),
    columnHelper.accessor("collection_date", {
      header: "Collection Date",
      cell: (info) => {
        const val = info.getValue() as string;
        return <span className="text-slate-700">{formatDate(val)}</span>;
      },
    }),
    columnHelper.accessor("refund_date", {
      header: "Refund Date",
      cell: (info) => {
        const val = info.getValue() as string;
        return <span className="text-slate-600">{formatDate(val)}</span>;
      },
    }),
    columnHelper.accessor("notes", {
      header: "Catatan",
      cell: (info) => <span className="text-xs text-slate-500">{info.getValue() || "—"}</span>,
    }),
  ];

  const table = useReactTable({
    data: data || [],
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  return (
    <div className="rounded-xl border border-slate-200 bg-white overflow-hidden shadow-sm">
      <table className="w-full text-sm text-left">
        <thead className="border-b border-slate-200 bg-slate-50/75 text-slate-600 font-semibold">
          {table.getHeaderGroups().map((headerGroup) => (
            <tr key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <th key={header.id} className="px-5 py-3.5">
                  {flexRender(
                    header.column.columnDef.header,
                    header.getContext()
                  )}
                </th>
              ))}
            </tr>
          ))}
        </thead>
        <tbody className="divide-y divide-slate-100">
          {table.getRowModel().rows.map((row) => (
            <tr
              key={row.id}
              className="hover:bg-orange/5 cursor-pointer transition-colors"
              onClick={() => onRowClick?.(row.original)}
            >
              {row.getVisibleCells().map((cell) => (
                <td key={cell.id} className="px-5 py-4">
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </td>
              ))}
            </tr>
          ))}
          {table.getRowModel().rows.length === 0 && (
            <tr>
              <td colSpan={columns.length} className="px-5 py-12 text-center text-slate-400">
                No data found.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}
