// Code generated by epmp-sdk. DO NOT EDIT.

package dto

import "time"

// CreateInvoiceRequest is the DTO for creating a Invoice.
type CreateInvoiceRequest struct {
	OrganizationId string `json:"organization_id"`
	ContractId string `json:"contract_id"`
	TenantId string `json:"tenant_id"`
	Amount float64 `json:"amount"`
	Status string `json:"status"`
	DueDate time.Time `json:"due_date"`
	PaidDate time.Time `json:"paid_date"`
	PaymentMethod string `json:"payment_method"`
	Notes string `json:"notes"`
}

// UpdateInvoiceRequest is the DTO for updating a Invoice.
type UpdateInvoiceRequest struct {
	OrganizationId string `json:"organization_id"`
	ContractId string `json:"contract_id"`
	TenantId string `json:"tenant_id"`
	Amount float64 `json:"amount"`
	Status string `json:"status"`
	DueDate time.Time `json:"due_date"`
	PaidDate time.Time `json:"paid_date"`
	PaymentMethod string `json:"payment_method"`
	Notes string `json:"notes"`
}

// InvoiceResponse is the DTO for returning a Invoice.
type InvoiceResponse struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	ContractId string `json:"contract_id"`
	TenantId string `json:"tenant_id"`
	Amount float64 `json:"amount"`
	Status string `json:"status"`
	DueDate time.Time `json:"due_date"`
	PaidDate time.Time `json:"paid_date"`
	PaymentMethod string `json:"payment_method"`
	Notes string `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// InvoiceListResponse is the DTO for a paginated list of Invoice.
type InvoiceListResponse struct {
	Data       []InvoiceResponse `json:"data"`
	Total      int64               `json:"total"`
	Page       int                 `json:"page"`
	PerPage    int                 `json:"per_page"`
	TotalPages int                 `json:"total_pages"`
}
