// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate, useParams } from "react-router-dom";
import { useOccupancy, useUpdateOccupancy } from "../hooks";
import { OccupancyForm } from "../components/OccupancyForm";
import type { CreateOccupancyFormData } from "../schema";

export function OccupancyEditPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useOccupancy(id);
  const updateMutation = useUpdateOccupancy();

  const handleSubmit = (formData: CreateOccupancyFormData) => {
    updateMutation.mutate(
      { id: id!, data: formData },
      { onSuccess: () => navigate(`/occupancy/${id}`) }
    );
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">Edit Occupancy</h1>
      <OccupancyForm
        onSubmit={handleSubmit}
        defaultValues={data}
        isSubmitting={updateMutation.isPending}
      />
    </div>
  );
}
