// Code generated by epmp-sdk. DO NOT EDIT.

import { useParams, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useOccupancy, useDeleteOccupancy } from "../hooks";

export function OccupancyDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useOccupancy(id);
  const deleteMutation = useDeleteOccupancy();

  const handleDelete = () => {
    if (!confirm("Are you sure you want to delete this occupancy?")) return;
    deleteMutation.mutate(id!, {
      onSuccess: () => navigate("/occupancy"),
    });
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Occupancy Detail</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => navigate("/occupancy")}>
            Back
          </Button>
          <Button variant="outline" onClick={() => navigate(`/occupancy/${id}/edit`)}>
            Edit
          </Button>
          <Button variant="destructive" onClick={handleDelete}>
            Delete
          </Button>
        </div>
      </div>

      <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">OrganizationId</dt>
          <dd className="text-sm">{String(data.organization_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Id</dt>
          <dd className="text-sm">{String(data.id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">ContractId</dt>
          <dd className="text-sm">{String(data.contract_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">RoomId</dt>
          <dd className="text-sm">{String(data.room_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">TenantId</dt>
          <dd className="text-sm">{String(data.tenant_id ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Status</dt>
          <dd className="text-sm">{String(data.status ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">CheckInTime</dt>
          <dd className="text-sm">{String(data.check_in_time ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">CheckOutTime</dt>
          <dd className="text-sm">{String(data.check_out_time ?? "—")}</dd>
        </div>
        <div className="space-y-1">
          <dt className="text-sm font-medium text-gray-500">Notes</dt>
          <dd className="text-sm">{String(data.notes ?? "—")}</dd>
        </div>
      </dl>
    </div>
  );
}
