// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/tenantidentity/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// TenantIdentityRepositoryImpl implements TenantIdentityRepository using PostgreSQL.
type TenantIdentityRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewTenantIdentityRepositoryImpl creates a new TenantIdentityRepositoryImpl.
func NewTenantIdentityRepositoryImpl(db *pgxpool.Pool) *TenantIdentityRepositoryImpl {
	return &TenantIdentityRepositoryImpl{db: db}
}

// Ensure TenantIdentityRepositoryImpl implements domain repository interface.
var _ TenantIdentityRepository = (*TenantIdentityRepositoryImpl)(nil)

func (r *TenantIdentityRepositoryImpl) Save(ctx context.Context, e *entity.TenantIdentity) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO tenant_identities (organization_id, tenant_id, identity_type, identity_number, file_url)
			VALUES ($1, $2, $3, $4, $5)
			RETURNING id`,
			e.OrganizationId, e.TenantId, e.IdentityType, e.IdentityNumber, e.FileUrl,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE tenant_identities
		SET    organization_id=$1, tenant_id=$2, identity_type=$3, identity_number=$4, file_url=$5
		WHERE  id=$6 AND deleted_at IS NULL`,
		e.OrganizationId, e.TenantId, e.IdentityType, e.IdentityNumber, e.FileUrl, e.Id,
	)
	return err
}

func (r *TenantIdentityRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.TenantIdentity, error) {
	e := &entity.TenantIdentity{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, tenant_id, identity_type, identity_number, file_url, deleted_at
		FROM   tenant_identities
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.TenantId, &e.IdentityType, &e.IdentityNumber, &e.FileUrl, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("tenantidentity repository: find by id: %w", err)
	}
	return e, nil
}

func (r *TenantIdentityRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.TenantIdentity, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, tenant_id, identity_type, identity_number, file_url, deleted_at
		FROM   tenant_identities
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("tenantidentity repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.TenantIdentity
	for rows.Next() {
		e := &entity.TenantIdentity{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.TenantId, &e.IdentityType, &e.IdentityNumber, &e.FileUrl, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *TenantIdentityRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE tenant_identities SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
