// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate, useParams } from "react-router-dom";
import { useAssetInspection, useUpdateAssetInspection } from "../hooks";
import { AssetInspectionForm } from "../components/AssetInspectionForm";
import type { CreateAssetInspectionFormData } from "../schema";

export function AssetInspectionEditPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useAssetInspection(id);
  const updateMutation = useUpdateAssetInspection();

  const handleSubmit = (formData: CreateAssetInspectionFormData) => {
    updateMutation.mutate(
      { id: id!, data: formData },
      { onSuccess: () => navigate(`/assetinspection/${id}`) }
    );
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">Edit AssetInspection</h1>
      <AssetInspectionForm
        onSubmit={handleSubmit}
        defaultValues={data}
        isSubmitting={updateMutation.isPending}
      />
    </div>
  );
}
