// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/tenant/domain/entity"
)

// TenantRepository is the contract for persisting Tenant aggregates.
type TenantRepository interface {
	// Save persists a Tenant entity.
	Save(ctx context.Context, e *entity.Tenant) error

	// FindByID retrieves a Tenant by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Tenant, error)

	// FindAll retrieves a paginated list of Tenant entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Tenant, error)

	// Delete removes a Tenant by its primary key.
	Delete(ctx context.Context, id string) error
}
