// Code generated by epmp-sdk. DO NOT EDIT.

package entity

import "time"

// TenantIdentity is the domain entity for tenantidentity.
type TenantIdentity struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	IdentityType string `json:"identity_type"`
	IdentityNumber string `json:"identity_number"`
	FileUrl string `json:"file_url"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewTenantIdentity creates a new TenantIdentity instance.
func NewTenantIdentity() *TenantIdentity {
	return &TenantIdentity{}
}
