// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const adjustmentSchema = z.object({
  organization_id: z.string(),
  id: z.string(),
  invoice_id: z.string(),
  adjustment_type: z.enum(["Credit", "Debit"]),
  amount: z.number(),
  adjustment_date: z.string(),
  reason: z.string(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createAdjustmentSchema = adjustmentSchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export const updateAdjustmentSchema = createAdjustmentSchema.partial();

export type AdjustmentFormData = z.infer<typeof adjustmentSchema>;
export type CreateAdjustmentFormData = z.infer<typeof createAdjustmentSchema>;
export type UpdateAdjustmentFormData = z.infer<typeof updateAdjustmentSchema>;
