// Code generated by epmp-sdk. DO NOT EDIT.

package dto

import "time"

// CreateReservationRequest is the DTO for creating a Reservation.
type CreateReservationRequest struct {
	OrganizationId string `json:"organization_id"`
	TenantId string `json:"tenant_id"`
	PropertyId string `json:"property_id"`
	RoomId string `json:"room_id"`
	Status string `json:"status"`
	CheckInDate time.Time `json:"check_in_date"`
	CheckOutDate time.Time `json:"check_out_date"`
	BookingFee float64 `json:"booking_fee"`
	Notes string `json:"notes"`
}

// UpdateReservationRequest is the DTO for updating a Reservation.
type UpdateReservationRequest struct {
	OrganizationId string `json:"organization_id"`
	TenantId string `json:"tenant_id"`
	PropertyId string `json:"property_id"`
	RoomId string `json:"room_id"`
	Status string `json:"status"`
	CheckInDate time.Time `json:"check_in_date"`
	CheckOutDate time.Time `json:"check_out_date"`
	BookingFee float64 `json:"booking_fee"`
	Notes string `json:"notes"`
}

// ReservationResponse is the DTO for returning a Reservation.
type ReservationResponse struct {
	OrganizationId string `json:"organization_id"`
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	PropertyId string `json:"property_id"`
	RoomId string `json:"room_id"`
	Status string `json:"status"`
	CheckInDate time.Time `json:"check_in_date"`
	CheckOutDate time.Time `json:"check_out_date"`
	BookingFee float64 `json:"booking_fee"`
	Notes string `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ReservationListResponse is the DTO for a paginated list of Reservation.
type ReservationListResponse struct {
	Data       []ReservationResponse `json:"data"`
	Total      int64               `json:"total"`
	Page       int                 `json:"page"`
	PerPage    int                 `json:"per_page"`
	TotalPages int                 `json:"total_pages"`
}
