// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateTenantIdentity } from "../hooks";
import { TenantIdentityForm } from "../components/TenantIdentityForm";
import type { CreateTenantIdentityFormData } from "../schema";

export function TenantIdentityCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateTenantIdentity();

  const handleSubmit = (data: CreateTenantIdentityFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/tenantidentity"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New TenantIdentity</h1>
      <TenantIdentityForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
