// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/room/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// RoomRepositoryImpl implements RoomRepository using PostgreSQL.
type RoomRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewRoomRepositoryImpl creates a new RoomRepositoryImpl.
func NewRoomRepositoryImpl(db *pgxpool.Pool) *RoomRepositoryImpl {
	return &RoomRepositoryImpl{db: db}
}

// Ensure RoomRepositoryImpl implements domain repository interface.
var _ RoomRepository = (*RoomRepositoryImpl)(nil)

func (r *RoomRepositoryImpl) Save(ctx context.Context, e *entity.Room) error {
	// TODO: implement with sqlc queries
	return fmt.Errorf("room repository: Save not implemented")
}

func (r *RoomRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.Room, error) {
	// TODO: implement with sqlc queries
	return nil, fmt.Errorf("room repository: FindByID not implemented")
}

func (r *RoomRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.Room, error) {
	// TODO: implement with sqlc queries
	return nil, fmt.Errorf("room repository: FindAll not implemented")
}

func (r *RoomRepositoryImpl) Delete(ctx context.Context, id string) error {
	// TODO: implement with sqlc queries
	return fmt.Errorf("room repository: Delete not implemented")
}
