// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/epmp/backend/internal/modules/room/entity"
)

// RoomRepository is the contract for persisting Room aggregates.
type RoomRepository interface {
	// Save persists a Room entity.
	Save(ctx context.Context, e *entity.Room) error

	// FindByID retrieves a Room by its primary key.
	FindByID(ctx context.Context, id string) (*entity.Room, error)

	// FindAll retrieves a paginated list of Room entities.
	FindAll(ctx context.Context, limit, offset int) ([]*entity.Room, error)

	// Delete removes a Room by its primary key.
	Delete(ctx context.Context, id string) error
}
