// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate, useParams } from "react-router-dom";
import { useRefund, useUpdateRefund } from "../hooks";
import { RefundForm } from "../components/RefundForm";
import type { CreateRefundFormData } from "../schema";

export function RefundEditPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useRefund(id);
  const updateMutation = useUpdateRefund();

  const handleSubmit = (formData: CreateRefundFormData) => {
    updateMutation.mutate(
      { id: id!, data: formData },
      { onSuccess: () => navigate(`/refund/${id}`) }
    );
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">Edit Refund</h1>
      <RefundForm
        onSubmit={handleSubmit}
        defaultValues={data}
        isSubmitting={updateMutation.isPending}
      />
    </div>
  );
}
