// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate, useParams } from "react-router-dom";
import { useAssetAssignment, useUpdateAssetAssignment } from "../hooks";
import { AssetAssignmentForm } from "../components/AssetAssignmentForm";
import type { CreateAssetAssignmentFormData } from "../schema";

export function AssetAssignmentEditPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data, isLoading } = useAssetAssignment(id);
  const updateMutation = useUpdateAssetAssignment();

  const handleSubmit = (formData: CreateAssetAssignmentFormData) => {
    updateMutation.mutate(
      { id: id!, data: formData },
      { onSuccess: () => navigate(`/assetassignment/${id}`) }
    );
  };

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Not found</div>;

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">Edit AssetAssignment</h1>
      <AssetAssignmentForm
        onSubmit={handleSubmit}
        defaultValues={data}
        isSubmitting={updateMutation.isPending}
      />
    </div>
  );
}
