// @ts-nocheck
// Code generated by epmp-sdk. DO NOT EDIT.

import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AssetAssignmentTable } from "../components/AssetAssignmentTable";
import { useAssetAssignments, useDeleteAssetAssignment } from "../hooks";
import { Plus } from "lucide-react";
import type { AssetAssignment } from "../types";

export function AssetAssignmentListPage() {
  const navigate = useNavigate();
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [searchInput, setSearchInput] = useState("");

  const { data, isLoading } = useAssetAssignments({
    page,
    per_page: 20,
    search: search || undefined,
  });

  const deleteMutation = useDeleteAssetAssignment();

  const handleRowClick = (row: AssetAssignment) => {
    navigate(`/dashboard/asset-assignments/${row.id}`);
  };
  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setSearch(searchInput);
    setPage(1);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-slate-900">AssetAssignments</h1>
        <Button onClick={() => navigate("/dashboard/asset-assignments/new")}>
          <Plus className="w-4 h-4 mr-1" />
          New AssetAssignment
        </Button>
      </div>
      <form onSubmit={handleSearch} className="flex gap-2">
        <Input
          placeholder="Search assetassignments..."
          value={searchInput}
          onChange={(e) => setSearchInput(e.target.value)}
          className="max-w-sm"
        />
        <Button type="submit" variant="outline">Search</Button>
      </form>

      {isLoading ? (
        <div className="text-center py-12 text-slate-400">Loading assetassignments...</div>
      ) : (
        <>
          <AssetAssignmentTable data={data?.data ?? []} onRowClick={handleRowClick} />

          {data && data.total_pages > 1 && (
            <div className="flex items-center justify-between">
              <p className="text-sm text-slate-500">
                Page {data.page} of {data.total_pages} ({data.total} total)
              </p>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  disabled={page <= 1}
                  onClick={() => setPage(page - 1)}
                >
                  Previous
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  disabled={page >= data.total_pages}
                  onClick={() => setPage(page + 1)}
                >
                  Next
                </Button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
