// Code generated by epmp-sdk. DO NOT EDIT.

package repository

import (
	"context"
	"fmt"

	"github.com/epmp/backend/internal/modules/assetinspection/entity"

	"github.com/jackc/pgx/v5/pgxpool"
)

// AssetInspectionRepositoryImpl implements AssetInspectionRepository using PostgreSQL.
type AssetInspectionRepositoryImpl struct {
	db *pgxpool.Pool
}

// NewAssetInspectionRepositoryImpl creates a new AssetInspectionRepositoryImpl.
func NewAssetInspectionRepositoryImpl(db *pgxpool.Pool) *AssetInspectionRepositoryImpl {
	return &AssetInspectionRepositoryImpl{db: db}
}

// Ensure AssetInspectionRepositoryImpl implements domain repository interface.
var _ AssetInspectionRepository = (*AssetInspectionRepositoryImpl)(nil)

func (r *AssetInspectionRepositoryImpl) Save(ctx context.Context, e *entity.AssetInspection) error {
	if e.Id == "" {
		// INSERT
		err := r.db.QueryRow(ctx, `
			INSERT INTO asset_inspections (organization_id, asset_id, inspection_date, condition, notes)
			VALUES ($1, $2, $3, $4, $5)
			RETURNING id`,
			e.OrganizationId, e.AssetId, e.InspectionDate, e.Condition, e.Notes,
		).Scan(&e.Id)
		return err
	}
	// UPDATE
	// Note: id is dynamically added as the last argument in Exec for UPDATE
	_, err := r.db.Exec(ctx, `
		UPDATE asset_inspections
		SET    organization_id=$1, asset_id=$2, inspection_date=$3, condition=$4, notes=$5
		WHERE  id=$6 AND deleted_at IS NULL`,
		e.OrganizationId, e.AssetId, e.InspectionDate, e.Condition, e.Notes, e.Id,
	)
	return err
}

func (r *AssetInspectionRepositoryImpl) FindByID(ctx context.Context, id string) (*entity.AssetInspection, error) {
	e := &entity.AssetInspection{}
	err := r.db.QueryRow(ctx, `
		SELECT organization_id, id, asset_id, inspection_date, condition, notes, deleted_at
		FROM   asset_inspections
		WHERE  id = $1 AND deleted_at IS NULL`,
		id,
	).Scan(&e.OrganizationId, &e.Id, &e.AssetId, &e.InspectionDate, &e.Condition, &e.Notes, &e.DeletedAt)
	
	if err != nil {
		return nil, fmt.Errorf("assetinspection repository: find by id: %w", err)
	}
	return e, nil
}

func (r *AssetInspectionRepositoryImpl) FindAll(ctx context.Context, limit, offset int) ([]*entity.AssetInspection, error) {
	rows, err := r.db.Query(ctx, `
		SELECT organization_id, id, asset_id, inspection_date, condition, notes, deleted_at
		FROM   asset_inspections
		WHERE  deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`,
		limit, offset,
	)
	if err != nil {
		return nil, fmt.Errorf("assetinspection repository: find all: %w", err)
	}
	defer rows.Close()

	var list []*entity.AssetInspection
	for rows.Next() {
		e := &entity.AssetInspection{}
		if err := rows.Scan(&e.OrganizationId, &e.Id, &e.AssetId, &e.InspectionDate, &e.Condition, &e.Notes, &e.DeletedAt); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

func (r *AssetInspectionRepositoryImpl) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE asset_inspections SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL`, id)
	return err
}
