// Code generated by epmp-sdk. DO NOT EDIT.

import { useNavigate } from "react-router-dom";
import { useCreateBed } from "../hooks";
import { BedForm } from "../components/BedForm";
import type { CreateBedFormData } from "../schema";

export function BedCreatePage() {
  const navigate = useNavigate();
  const createMutation = useCreateBed();

  const handleSubmit = (data: CreateBedFormData) => {
    createMutation.mutate(data, {
      onSuccess: () => navigate("/bed"),
    });
  };

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold">New Bed</h1>
      <BedForm
        onSubmit={handleSubmit}
        isSubmitting={createMutation.isPending}
      />
    </div>
  );
}
