// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Refund,
  RefundListResponse,
  CreateRefundRequest,
  UpdateRefundRequest,
  RefundQueryParams,
} from "../types";

const BASE_PATH = "/refunds";
export async function fetchRefunds(params?: RefundQueryParams): Promise<RefundListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: RefundListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchRefundById(id: string): Promise<Refund> {
  const res = await api.get<{ success: boolean; data: Refund }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createRefund(data: CreateRefundRequest): Promise<Refund> {
  const res = await api.post<{ success: boolean; data: Refund }>(BASE_PATH, data);
  return res.data;
}
export async function updateRefund(id: string, data: UpdateRefundRequest): Promise<Refund> {
  const res = await api.put<{ success: boolean; data: Refund }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteRefund(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
