// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Refund,
  RefundListResponse,
  CreateRefundRequest,
  UpdateRefundRequest,
  RefundQueryParams,
} from "../types";

const BASE_PATH = "/api/refunds";
export async function fetchRefunds(params?: RefundQueryParams): Promise<RefundListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<RefundListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchRefundById(id: string): Promise<Refund> {
  return api.get<Refund>(`${BASE_PATH}/${id}`);
}
export async function createRefund(data: CreateRefundRequest): Promise<Refund> {
  return api.post<Refund>(BASE_PATH, data);
}
export async function updateRefund(id: string, data: UpdateRefundRequest): Promise<Refund> {
  return api.put<Refund>(`${BASE_PATH}/${id}`, data);
}
export async function deleteRefund(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
