// Code generated by epmp-sdk. DO NOT EDIT.

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useInvoices } from "@/features/billing/hooks";
import { useTenants } from "@/features/tenant/hooks";
import {
  createPaymentSchema,
  type CreatePaymentFormData,
} from "../schema";

interface PaymentFormProps {
  onSubmit: (data: CreatePaymentFormData) => void;
  defaultValues?: Partial<CreatePaymentFormData>;
  isSubmitting?: boolean;
}

export function PaymentForm({
  onSubmit,
  defaultValues,
  isSubmitting,
}: PaymentFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreatePaymentFormData>({
    resolver: zodResolver(createPaymentSchema),
    defaultValues: {
      payment_method: "Transfer",
      status: "Pending",
      payment_date: new Date().toISOString().split("T")[0],
      ...defaultValues,
    },
  });

  const { data: invoicesData } = useInvoices({ per_page: 100 });
  const { data: tenantsData } = useTenants({ per_page: 100 });
  const invoices = invoicesData?.data || [];
  const tenants = tenantsData?.data || [];

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      <div className="space-y-2">
        <Label htmlFor="invoice_id">Invoice</Label>
        <select
          id="invoice_id"
          {...register("invoice_id")}
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm bg-white text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange"
        >
          <option value="">Select an invoice...</option>
          {invoices.map((inv) => (
            <option key={inv.id} value={inv.id}>
              Invoice #{inv.id.slice(0, 8)} - Rp {Number(inv.amount || 0).toLocaleString()} ({inv.status})
            </option>
          ))}
        </select>
        {errors.invoice_id && (
          <p className="text-xs text-red-600 mt-1">{errors.invoice_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="tenant_id">Tenant</Label>
        <select
          id="tenant_id"
          {...register("tenant_id")}
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm bg-white text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange"
        >
          <option value="">Select a tenant...</option>
          {tenants.map((t) => (
            <option key={t.id} value={t.id}>
              {t.full_name} ({t.email || t.phone})
            </option>
          ))}
        </select>
        {errors.tenant_id && (
          <p className="text-xs text-red-600 mt-1">{errors.tenant_id.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="amount">Amount</Label>
        <Input
          id="amount"
          type="number"
          step="any"
          min="0"
          placeholder="0.00"
          {...register("amount", { valueAsNumber: true })}
        />
        {errors.amount && (
          <p className="text-xs text-red-600 mt-1">{errors.amount.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="payment_date">Payment Date</Label>
        <Input
          id="payment_date"
          type="date"
          {...register("payment_date")}
        />
        {errors.payment_date && (
          <p className="text-xs text-red-600 mt-1">{errors.payment_date.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="payment_method">Payment Method</Label>
        <select
          id="payment_method"
          {...register("payment_method")}
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm bg-white text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange"
        >
          <option value="Transfer">Transfer</option>
          <option value="CreditCard">CreditCard</option>
          <option value="Cash">Cash</option>
          <option value="EWallet">EWallet</option>
        </select>
        {errors.payment_method && (
          <p className="text-xs text-red-600 mt-1">{errors.payment_method.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="status">Status</Label>
        <select
          id="status"
          {...register("status")}
          className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm bg-white text-slate-900 focus:outline-none focus:ring-2 focus:ring-orange"
        >
          <option value="Pending">Pending</option>
          <option value="Success">Success</option>
          <option value="Failed">Failed</option>
          <option value="Refunded">Refunded</option>
        </select>
        {errors.status && (
          <p className="text-xs text-red-600 mt-1">{errors.status.message}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor="reference_number">Reference Number</Label>
        <Input
          id="reference_number"
          placeholder="e.g. TRX-12345"
          {...register("reference_number")}
        />
        {errors.reference_number && (
          <p className="text-xs text-red-600 mt-1">{errors.reference_number.message}</p>
        )}
      </div>

      <Button type="submit" disabled={isSubmitting} className="bg-orange hover:bg-orange/90 text-white w-full sm:w-auto">
        {isSubmitting ? "Saving..." : "Save"}
      </Button>
    </form>
  );
}
