// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  TenantDocument,
  TenantDocumentListResponse,
  CreateTenantDocumentRequest,
  UpdateTenantDocumentRequest,
  TenantDocumentQueryParams,
} from "../types";

const BASE_PATH = "/tenant_documents";
export async function fetchTenantDocuments(params?: TenantDocumentQueryParams): Promise<TenantDocumentListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  const res = await api.get<{ success: boolean; data: TenantDocumentListResponse }>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
  return res.data;
}
export async function fetchTenantDocumentById(id: string): Promise<TenantDocument> {
  const res = await api.get<{ success: boolean; data: TenantDocument }>(`${BASE_PATH}/${id}`);
  return res.data;
}
export async function createTenantDocument(data: CreateTenantDocumentRequest): Promise<TenantDocument> {
  const res = await api.post<{ success: boolean; data: TenantDocument }>(BASE_PATH, data);
  return res.data;
}
export async function updateTenantDocument(id: string, data: UpdateTenantDocumentRequest): Promise<TenantDocument> {
  const res = await api.put<{ success: boolean; data: TenantDocument }>(`${BASE_PATH}/${id}`, data);
  return res.data;
}
export async function deleteTenantDocument(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
