// Code generated by epmp-sdk. DO NOT EDIT.

import { z } from "zod";

export const organizationSchema = z.object({
  id: z.string(),
  name: z.string().max(100),
  domain: z.string().max(100),
  is_active: z.boolean(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createOrganizationSchema = organizationSchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export const updateOrganizationSchema = createOrganizationSchema.partial();

export type OrganizationFormData = z.infer<typeof organizationSchema>;
export type CreateOrganizationFormData = z.infer<typeof createOrganizationSchema>;
export type UpdateOrganizationFormData = z.infer<typeof updateOrganizationSchema>;
