// Code generated by epmp-sdk. DO NOT EDIT.

import { api, ApiError } from "@/services/api";
import type {
  Payment,
  PaymentListResponse,
  CreatePaymentRequest,
  UpdatePaymentRequest,
  PaymentQueryParams,
} from "../types";

const BASE_PATH = "/api/payments";
export async function fetchPayments(params?: PaymentQueryParams): Promise<PaymentListResponse> {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.per_page) query.set("per_page", String(params.per_page));
  if (params?.sort) query.set("sort", params.sort);
  if (params?.order) query.set("order", params.order);
  if (params?.search) query.set("search", params.search);
  const qs = query.toString();
  return api.get<PaymentListResponse>(`${BASE_PATH}${qs ? `?${qs}` : ""}`);
}
export async function fetchPaymentById(id: string): Promise<Payment> {
  return api.get<Payment>(`${BASE_PATH}/${id}`);
}
export async function createPayment(data: CreatePaymentRequest): Promise<Payment> {
  return api.post<Payment>(BASE_PATH, data);
}
export async function updatePayment(id: string, data: UpdatePaymentRequest): Promise<Payment> {
  return api.put<Payment>(`${BASE_PATH}/${id}`, data);
}
export async function deletePayment(id: string): Promise<void> {
  return api.delete<void>(`${BASE_PATH}/${id}`);
}

export { ApiError };
